### ISSUE TITLE
`glibc` is old, causes PR builds to fail (sdkman in Java, Rust, etc.)

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#1016]
### Bug description

When we try to run from a Gitpod workspace in [this branch](https://github.com/gitpod-io/workspace-images/tree/kylos101/update-dazzle):
```
gitpod /workspace/workspace-images (kylos101/update-dazzle) $ docker run --rm -it localhost:5000/dazzle:lang-java-11--b4357525b55d483a0a948366cbfeddd16deefb8055fdddec3abbd4318119e155--test
Unable to find image 'localhost:5000/dazzle:lang-java-11--b4357525b55d483a0a948366cbfeddd16deefb8055fdddec3abbd4318119e155--test' locally
lang-java-11--b4357525b55d483a0a948366cbfeddd16deefb8055fdddec3abbd4318119e155--test: Pulling from dazzle
846c0b181fff: Already exists 
8ece640f49fb: Already exists 
c02424bb37bc: Already exists 
2208c2c67be3: Already exists 
9767d8dd0a1b: Already exists 
bd5bb49c4031: Pull complete 
8779351decd9: Pull complete 
dd76b16e81dd: Pull complete 
f8947c1608e3: Pull complete 
9c8bfa43c5ea: Pull complete 
bce972e3dda8: Pull complete 
4f4fb700ef54: Pull complete 
fdeaf2764fde: Pull complete 
4fc99b8e7d9f: Pull complete 
8319be1c2773: Pull complete 
766805260ed7: Pull complete 
54c1de2f096d: Pull complete 
143c067030fa: Pull complete 
Digest: sha256:36948cce21e0dc9f16a581e26325fdf3706c3c8da878798e5805773c6e75744f
Status: Downloaded newer image for localhost:5000/dazzle:lang-java-11--b4357525b55d483a0a948366cbfeddd16deefb8055fdddec3abbd4318119e155--test
gitpod ~ $ ldd --version ldd
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
gitpod ~ $ sdk v
/home/gitpod/.sdkman/libexec/version: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/gitpod/.sdkman/libexec/version)
/home/gitpod/.sdkman/libexec/version: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/gitpod/.sdkman/libexec/version)
/home/gitpod/.sdkman/libexec/version: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/gitpod/.sdkman/libexec/version)
```

The error looks like:
```
              failed                                      message="assertion failed: status == 0" result="&test.RunResult{Stdout: []byte(""), Stderr: []byte("/home/gitpod/.sdkman/libexec/version: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/gitpod/.sdkman/libexec/version)\n/home/gitpod/.sdkman/libexec/version: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/gitpod/.sdkman/libexec/version)\n/home/gitpod/.sdkman/libexec/version: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/gitpod/.sdkman/libexec/version)\n"), StatusCode: 1}" 
```

The version of libc we're shipping in workspaces is old:
```
gitpod ~ $ ldd --version ldd
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

It is installed in [`build-essential`](https://askubuntu.com/a/1299830).

### Steps to reproduce

Rerun this failed job, or, try to build the `java-11` combo.

### Expected behavior

It should work

**Comment by kylos101** [comment]
We can install additional versions of glibc:
https://stackoverflow.com/a/73188338

And manage related software software, including setting `LD_LIBRARY_PATH`:
https://stackoverflow.com/a/851229

Another option is to change the OS on the base image. But, that could potentially be breaking for customers. :grimacing:

**Comment by gengjiawen** [comment]
@kylos101 This basically block everything, is there a quick fix going on ?

**Comment by kylos101** [comment]
> @kylos101 This basically block everything, is there a quick fix going on ?

Thanks for raising the question, @gengjiawen ! :pray: I've pinned this issue for posterity. As a short term solution, folks should be able to [build a custom image](https://www.gitpod.io/docs/configure/workspaces/workspace-image#custom-base-image) using jammy. We are pursuing that as a long term solution for later this month. More updates to follow. For example, when will the images supporting Jammy be available for users to test beforehand.

**Comment by kylos101** [comment]
Also, I encourage folks to subscribe to this issue for updates. :pray:

**Comment by gengjiawen** [comment]
> As a short term solution, folks should be able to [build a custom image](https://www.gitpod.io/docs/configure/workspaces/workspace-image#custom-base-image) using jammy.

It's not main issue. It's blocking all fix and feature being merged and deployed for `workspace-image`.

Maybe we can lock sdkman to old version to fix glibc issue ?

**Comment by kylos101** [comment]
:wave: @gengjiawen , [we're updating to Jammy in a couple weeks](https://www.gitpod.io/changelog#workspace-images-os-and-node-versions-update). By updating to Jammy, we'll unblock fixes and features, but also find and resolve other issues. 

This new Jammy image will be available as a timestamped image before Feb 28 soon, and via `latest` tag on Feb 28.
