### ISSUE TITLE
Remove Python 2 by the end of 2019

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/workspace-images#106]
cf. https://github.com/python/devguide/pull/344

https://pythonclock.org/

**Comment by sr229** [comment]
Should be easy, I think I can take this one.

**Comment by AlexTugarev** [comment]
@sr229 this is just a reminder for now. Unfortunately some project relying no this. e.g. node-gyp support for python 3.7 is still wip, cf. https://github.com/nodejs/node/issues/25789

**Comment by jankeromnes** [comment]
I don't think it's Gitpod's role to nudge developers into changing/upgrading their code by pro-actively removing Python 2.

Instead I think we should be a tool that "just works", i.e. keep shipping with Python 2, allowing developers to migrate their projects in their own time.

Until Python 2 becomes impossible to install of course (e.g. when binaries are no longer available, or it becomes a big security problem like Flash was).
