### ISSUE TITLE
Transfer ownership of maintenance to IDE team

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#1064]
## Is your feature request related to a problem? Please describe

What is expected to do maintenance?
How will changes be available to customers?
Who owns related deployment?

## Describe the behaviour you'd like

IDE team owns maintenance for images.
Workspace team owns build and deploy pipeline.

## Describe alternatives you've considered

The code owners file is updated accordingly.
There may also be Github Action workflow files that need to be updated. For example, we auto inbox new issues.

**Comment by kylos101** [comment]
@laushinka is there a chamption from IDE team that I may be able to work with on this in an upcoming cycle? For example, to begin changing code-owners, for some (but not all) of the workspace-images repo, from workspace to IDE? Also, I'm not sure how y'all want to manage incoming issues for `workspace-images`, but having a feedback loop to check them would be beneficial. We used to use Gitpod Projects for this 🤔 .

**Comment by laushinka** [comment]
> is there a champion from IDE team
Hi, @kylos101! It will be @iQQBot and @filiptronicek. Since next week most of IDE will be off, how about the cycle of the second week of May?

**Comment by laushinka** [comment]
Btw should we move this issue to Linear?

**Comment by kylos101** [comment]
Closing so as we can do in Linear, thanks @laushinka , I missed [this](https://github.com/gitpod-io/workspace-images/issues/1064#issuecomment-1519705312).
