### ISSUE TITLE
Tasks are no longer running for Ubuntu 22.04 images

### ISSUE THREAD

**Issue by AaronDewes** [gitpod-io/workspace-images#1065]
### Bug description

Any images with Ubuntu 22.04 cause tasks to no longer run in prebuilts and workspaces. Instead, their command gets logged twice to the shell, then the bash prompt appears.

### Steps to reproduce

Use any image based on Ubuntu 22.04 and define tasks in a `.gitpod.yml`.

### Expected behavior

Tasks should be executed.

### Example repository

https://github.com/AaronDewes/gitpod-bug-example

### Anything else?

I'm not sure if this is the right repo or if this should be reported in the main gitpod repo, but considering it only started happening with recent images, I guess the bug might be here.

**Comment by axonasif** [comment]
Thanks for reporting @AaronDewes, it should be working after https://github.com/gitpod-io/workspace-images/actions/runs/4506401128 is done and new timestamped images are published.
