### ISSUE TITLE
default nginx not work error 404 not found 

### ISSUE THREAD

**Issue by eric23xa** [gitpod-io/workspace-images#1070]
hi 
again
I have issue with the installed of default version of  nginx 1.23 for gitpod  and also I install it with the >>>
apt update && apt full-upgrade -y 
sudo apt-get install build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev
wget http://nginx.org/download/nginx-1.20.2.tar.gz
tar -zxvf nginx-1.20.2.tar.gz
cd nginx-1.20.2
./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_gzip_static_module --with-cc-opt="-Wno-deprecated-declarations"
make
make install
........
and the the installation process was completed successfully and i get nginx/1.20.2 version and  nginx work with port 80 in default 
and get the  welcome page of nginx/1.20.2
but the problem is with php project not work 
I installed  php8.1-fpm and and start it and conv nginx to use it but It's useless also 
but when add php with html project in path 
/etc/nginx/html/project.php
and add html code to php as example 
nano /etc/nginx/html/project.php
cd /etc/nginx/html/
ls
rm -rf index.html
nano /etc/nginx/html/index.html
<html>
  <head>
    <title>PHP with HTML</title>
  </head>
  <body>
    <h1>Today's Date and Time</h1>
    <?php
      echo "The current date and time is: " . date("Y-m-d H:i:s");
    ?>
  </body>
</html>
It will work successfully under html .
thank you .

**Comment by Derroylo** [comment]
@eric23xa That sounds more like a configuration issue, then an issue with the images itself. It would also be great if you would use the code tags to mark the code/commands, it is very hard to read what you wrote.

If you just want to play around with php, then i suggest to take a look at this page: https://www.gitpod.io/docs/introduction/languages/php
They mostly use apache but that shouldn´t matter.
