### ISSUE TITLE
CHANGELOG is not updated

### ISSUE THREAD

**Issue by abitrolly** [gitpod-io/workspace-images#1107]
### Bug description

The last entry in https://github.com/gitpod-io/workspace-images/blob/main/CHANGELOG.md is from 2022-02-01 but https://hub.docker.com/r/gitpod/workspace-full/tags has quite a lot of tags from 2023 alone.

### Steps to reproduce

Go to https://github.com/gitpod-io/workspace-images/blob/main/CHANGELOG.md and try to find any of https://hub.docker.com/r/gitpod/workspace-full/tags

**Comment by filiptronicek** [comment]
Hi, I don't recall what the situation was back then, but since, we've kept the changelog pretty well up-to-date. Thanks!
