### ISSUE TITLE
Remove go cache from image.

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/workspace-images#122]
because it's unnecessary ~161MB.

![image](https://user-images.githubusercontent.com/239422/67554556-f34d2480-f70f-11e9-8867-f50e57d78415.png)

**Comment by jankeromnes** [comment]
https://github.com/gitpod-io/workspace-images/pull/121#issuecomment-546510409 said:

> Fixes #122
> Correctly merges the dpkg status files which avoids duplicate installation of the same packages.

and then got merged. Assuming this is fixed now.
