### ISSUE TITLE
Rust: don't include libs for linux-musl

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/workspace-images#124]
This can save ~450MB. 

I assume we don't need these libs because our base image (Debain) doesn't use musl. 
We'd need them if our base image would be alpine. 

![image](https://user-images.githubusercontent.com/239422/67555853-69528b00-f712-11e9-8eaf-31a979535d12.png)

**Comment by jankeromnes** [comment]
This essentially means reverting https://github.com/gitpod-io/workspace-images/pull/62

@meysholdt @geropl @JesterOrNot @RDIL What are the pros & cons of having `linux-musl` libs pre-installed in all Gitpod images by default?

(Well, one "con" is the ~450MB already mentioned by @meysholdt.)

**Comment by RDIL** [comment]
I'm no linux person, so I'm not sure what needs to be done here.

**Comment by RDIL** [comment]
Update: linux-musl allows rust devs to build their apps into binary cross-platform executables.  That is all I know.

**Comment by JesterOrNot** [comment]
What it does is it allows for true statically linked executables most rust executables require a system's local version of libc with musl you can link a system's version with the binary. Please see [the docs](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html) for more information.

**Comment by jankeromnes** [comment]
Thanks! And so, is it useful for every Gitpod user to always have musl by default in their workspace? Or is it ok to ask developers who need musl to create a custom Dockerfile to install it?

**Comment by JesterOrNot** [comment]
I suppose it is reasonable, but before removing it we should add how to install it in Gitpod to the docs.

**Comment by geropl** [comment]
I added it for the reason [@RDIL explained](https://github.com/gitpod-io/workspace-images/issues/124#issuecomment-620585302).

We don't need it for everyone, but - as @JesterOrNot suggested - add it to the docs in a section "How to develop Rust on Gitpod" because it's something a lot of Rust developers do.

**Comment by JesterOrNot** [comment]
@geropl that's already a thing https://www.gitpod.io/docs/languages/rust/ I meant add another section to the existing guide

**Comment by jankeromnes** [comment]
Many thanks for the explanations! I agree that we should:
- [ ] Briefly document in https://www.gitpod.io/docs/languages/rust/ how to cross-compile binaries by installing linux-musl
- [ ] Remove linux-musl from `gitpod/workspace-full`

**Comment by RDIL** [comment]
(If you really want to save space, switching from focal to buster saved me roughly 300 megabytes)

**Comment by sr229** [comment]
> (If you really want to save space, switching from focal to buster saved me roughly 300 megabytes)

Definitely not an option since Debian and Ubuntu are compiled differently. This is just simply removing musl libraries to trim off some dependencies which we don't need. We'd probably want a seperate image for musl as well.
