### ISSUE TITLE
sdk: command not found

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/workspace-images#127]
we're lost `sdk` on PATH :-(

cc. @32leaves

**Comment by svenefftinge** [comment]
I tested with https://github.com/gitpod-io/spring-petclinic earlier today. Why is it there?

**Comment by AlexTugarev** [comment]
Because there's a prebuilt.

**Comment by svenefftinge** [comment]
workaround:
```
bash ~/.sdkman/bin/sdkman-init.sh
```

**Comment by meysholdt** [comment]
Fixed via https://github.com/gitpod-io/workspace-images/commit/829609ab3003fc18b8cfb90f63f0bb05f0665666.
