### ISSUE TITLE
Fix the branch builds

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/workspace-images#13]

**Comment by orucky** [comment]
Should work now. See https://github.com/TypeFox/gitpod/issues/1822 for details.

**Comment by orucky** [comment]
The current behavior:
1. `master` builds with tags `latest` and `branch-master`
2. other branches build with tag `branch-<name-of-the-branch>`

In (2), disallowed characters in Docker tags are automatically converted to (AFAIR) underscores, so it should work fine for any branch regardless its name
