### ISSUE TITLE
Consider install the latest LTS version of Node.js

### ISSUE THREAD

**Issue by luizbills** [gitpod-io/workspace-images#132]
`nvm install --lts  --latest-npm` install latest LTS node.js and npm

**Comment by meysholdt** [comment]
@jankeromnes did https://github.com/gitpod-io/workspace-images/pull/117 fix this?

**Comment by luizbills** [comment]
Using `nvm install --lts` we won't have to keep updating manually every time.

**Comment by jankeromnes** [comment]
I much prefer @luizbills' approach, as it removes the need for us to constantly watch https://nodejs.org/ and manually update versions here.

However, with our new "dazzle" build this won't work well, as Dazzle caches each layer separately and forever, unless the `RUN` instruction is modified.

This means that switching to `nvm install --lts` will install the correct LTS once, but then that version will remained cached forever, even when newer versions come out.

**Comment by RDIL** [comment]
Fixed

**Comment by jankeromnes** [comment]
Indeed, thanks @RDIL!
