### ISSUE TITLE
Create a workspace-java-21 ?

### ISSUE THREAD

**Issue by jeanphi-baconnais** [gitpod-io/workspace-images#1342]
## Is your feature request related to a problem? Please describe
No

## Describe the behaviour you'd like
it's to create a Docker image for Java 21.

## Describe alternatives you've considered

I saw this image 21.0.3.fx-zulu which could be integrated in chunk file.

**Comment by filiptronicek** [comment]
@jeanphi-baconnais I totally agree, we should keep up with the LTS releases of Java. I created a PR for it, which should land this or next week.

**Comment by jeanphi-baconnais** [comment]
Thank you !
