### ISSUE TITLE
workspace-full has differing priorities for Python 3 libs and bins

### ISSUE THREAD

**Issue by rschroll** [gitpod-io/workspace-images#154]
I've built a repo that uses a Docker image based on workspace-full to install a Python 3 package called standardebooks (see rschroll/se-gitpod).  This package provides both a Python 3 library (called `se`) and a binary (also called `se`).  Everything got installed into `/home/gitpod/.pyenv/versions/3.7.6/`.  Then, in a running workspace I updated the standardebooks package.  The newer version got installed in `/workspace/.pip-modules/`.

Unfortunately, Python 3's import path and the shell's `$PATH` are inconsistent.  This results in the new version of the `se` library being loaded in Python, but the old version of the `se` binary being run from the shell.  Observe:
```bash
$ se version
1.0.27
$ python3 -c "import se; print(se.VERSION)"
1.0.28
```

I think the problem is related to the shims that pyenv creates for binaries.  If we check
```bash
$ which se
/home/gitpod/.pyenv/shims/se
```
We see the shim wins.  Looking at `$PATH`, we see
```
...
/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims
/home/gitpod/.pyenv/shims
...
/workspace/.pip-modules/bin
...
/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims
/home/gitpod/.pyenv/shims
...
/workspace/.pip-modules/bin
...
/home/gitpod/.pyenv/bin
/home/gitpod/.pyenv/shims
...
```

Regardless of the repeated lines, the shim wins.  Thus, we don't run the more recent binary:
```bash
$ /workspace/.pip-modules/bin/se version
1.0.28
```
This is the opposite of the python import path, with prioritizes the newer version:
```
>>> for p in sys.path: print(p)
/home/gitpod/.pyenv/versions/3.7.6/lib/python37.zip
/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7
/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/lib-dynload
/workspace/.pip-modules/lib/python3.7/site-packages
/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/site-packages
```
I would expect `$PATH` to be ordered in a similar manner.

**Comment by rschroll** [comment]
Looking a little deeper, the problem may be the ordering of the `.bashrc` file.  Early in the file, it prepends `/workspace/.pip-modules/bin` to the path.  At the end of the file, it runs the various bashrc.d files, which includes a `pyenv init -` command, which I assume sets up the `$PATH` with the pyenv shims.  It's not at all clear to me how the `.bashrc` file gets assembled, though, so I'm not sure what the best fix is.

**Comment by kylos101** [comment]
Hey @rschroll we recently introduced a [fix in dazzle](https://github.com/gitpod-io/workspace-images/pull/727) to correct path issues for `workspace-images`, like you shared in this issue.

```bash
Status: Downloaded newer image for gitpod/workspace-python:latest
gitpod ~ $ which python
/home/gitpod/.pyenv/shims/python
gitpod ~ $ which python3
/home/gitpod/.pyenv/shims/python3
```

Should be all set now. I'm going to close this issue, but, please reopen if you still have trouble?
