### ISSUE TITLE
Time to upgrade the Python language server

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/workspace-images#189]
While I might hate Palantir, I do think we need to update the PLS.  It is pinned on 0.25.0, which is roughly 2 years out-of-date.  

cc @jankeromnes @JesterOrNot as per usual 😄 

EDIT: Pull request now open!

**Comment by jankeromnes** [comment]
> Palantir

😱

> I do think we need to update the PLS. It is pinned on 0.25.0, which is roughly 2 years out-of-date.

No need to update it, since it was entirely removed from Gitpod in https://github.com/gitpod-io/workspace-images/commit/f2fe95173d79cf116411d3df2d52d8a5f2572676 😄 🔥

**Comment by RDIL** [comment]
Nice.
