### ISSUE TITLE
Write a test script

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/workspace-images#2]
we should have a build test, verifying the various expectations (e.g. executables and versions)

**Comment by orucky** [comment]
on that note I added a check that all files in the `gitpod` home are owned by gitpod:gitpod as part of the build (the last lines of the Dockerfile). It's something we depend on later, and it doesn't slow the build at all

**Comment by svenefftinge** [comment]
I think that should go into the gitpod layer that we put on top, no?

**Comment by jankeromnes** [comment]
I think this was fixed by https://github.com/gitpod-io/workspace-images/pull/121 🎉
