### ISSUE TITLE
Support JavaFX

### ISSUE THREAD

**Issue by hallvard** [gitpod-io/workspace-images#23]
Hi,

I tried using the workspace-full-vnc image for a simple JavaFX app, but got the following error:

Picked up JAVA_TOOL_OPTIONS: -Xmx3189m
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: nosuitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)

I've been able to get a JavaFX app running in a browser by connecting to a docker machine using the fcwu/docker-ubuntu-vnc-desktop image extended with openjdk11 and openjfx. Hence, somehow this provides a graphics pipeline that is supported. Would it be possible to support something similar in an image for gitpod? I don't know enough about linux and JavaFX to guess why, but perhaps you do?

**Comment by svenefftinge** [comment]
@32leaves added configuration for a JavaFX repository.
Configuration: https://github.com/gitpod-io/definitely-gp/commit/8609b986822c5ec660f39958e80b32c505c7718e
Try it out: https://gitpod.io/#https://github.com/RohitAwate/Everest

Let us know if that doesn't help.

**Comment by hallvard** [comment]
It worked! I should've checked out definitely-gp before creating the issue. Next time...
