### ISSUE TITLE
Install RipGrep

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/workspace-images#240]
Let's consider adding Ripgrep to our base image. See #186 and #76. CC @RDIL and @jankeromnes.

## Benefits
  - Fast workspace search

## Downsides
  - Possible duplication of install
  - Image size increace

**Comment by sr229** [comment]
Might be better we do it in the base image so we don't duplicate the installs.

**Comment by JesterOrNot** [comment]
@sr229 can you elaborate?

**Comment by aledbf** [comment]
Closing. Fixed in #444
