### ISSUE TITLE
[Legal Inquiry] Copyright on Workspace Images source code

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [gitpod-io/workspace-images#244]
I would like to ask if you have any plans to add a LICENSE for the Workspace Images Git repository in the future or should I seek legal advice and legal red tape to customize the Workspace Images files based on my needs?

**Comment by jankeromnes** [comment]
Hi @AndreiJirohHaliliDev2006, thank you for the great question! We intended these Dockerfiles to be fully open-source, but never added a LICENSE file.

So we are adding the MIT license in #248. Happy hacking, and thanks again!
