### ISSUE TITLE
[Community/Custom Image Builds] Where are the source files for 'gitpod/dazzle-wsfull-build'?

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/workspace-images#252]
Hi, friendly Gitpod staff! It's me again, Andrei.

I'm currently creating custom-made Gitpod workspace images by copying some code from here and add some customizations. During the CircleCI builds, the `./circleci/dazzle_build_image.sh` script complains that `manifest for gitpod/dazzle-wsfull-build:base-68a07315429db97200fafda52b288c03c711be3fb364c02dcbc38b86ca74172e not found`. I have only once question. Where are the source files for this sepcific image?

Thanks in advance!

Related CI logs for my repo: https://app.circleci.com/pipelines/github/ThePinsTeam-CustomImageBuilds/gp-workspace-with-sudo/3/workflows/c8f277c4-b72b-4148-97b6-a9fd0a0c699d
Full logs library: https://app.circleci.com/pipelines/github/ThePinsTeam-CustomImageBuilds/gp-workspace-with-sudo

**Comment by princerachit** [comment]
Since we have moved to dazzle v2 the mentioned image is not being used any more. Further, we do use GH actions instead of circle ci now.
