### ISSUE TITLE
Trying to install stable chrome version

### ISSUE THREAD

**Issue by snackattas** [gitpod-io/workspace-images#254]
I'm trying to install a stable chrome version for https://github.com/thepracticaldev/dev.to/blob/master/.gitpod.dockerfile

We need chrome in there because some of the unit tests use chrome headlessly.  

However, I'm struggling to add chrome in a dockerfile, since I believe chrome needs sudo permissions. Any idea how to accomplish this?

Thanks!

**Comment by snackattas** [comment]
I found this https://github.com/JesterOrNot/Gitpod-Chrome/blob/master/.gitpod.Dockerfile

But not sure we want to do a multi stage build...seems complicated to have all these dependencies

**Comment by sr229** [comment]
Isn't Live previews suffice enough? Shipping a full Chrome build doesn't really help much.

**Comment by snackattas** [comment]
Chrome is for running end to end tests with selenium, not for being used in the same way as Live previews.  Selenium needs the chrome browser to be installed. And the tests can be run headlessly.

Often if someone is using GitPod to do development, they may end up editing something that impacts unit tests, and some of those tests may use selenium. Not being able to run those kinds of tests in GitPod can be annoying.

**Comment by sr229** [comment]
Ah, don't we have a headless browser just for that purpose? I think NPM has that which should work just fine for selenium.

**Comment by snackattas** [comment]
chrome has a headless mode, which is what dev.to utilizes for its tests.

As well, the test suite is written in ruby, and it would be an effort to get it to be able to run with other browsers, when, chrome has a lot of the abilities we want for testing. You can see here, not a lot of options https://github.com/dhamaniasad/HeadlessBrowsers

As well, the tests use javascript so the browser choice needs to be able to load JS.  And using chrome in the suite is easy because lots of folks have it on their laptops. So its easy to use on their locals, and in TravisCI.  But not easy to use in Gitpod :(

**Comment by ret394** [comment]
- You do know they did not really want Chrome on their laptops? 
- Remember to test with Chromium and Firefox, please.
- I don't want to give a lecture to any more people in public about basics.

Does https://github.com/forem/forem have a decent REST API or is it on the list?

**Comment by DanielHabenicht** [comment]
Hi @sr229 I have come across the same problem as @snackattas. 

> Ah, don't we have a headless browser just for that purpose? I think NPM has that which should work just fine for selenium.

The puppeteer headless browser does not work out of the box in the `base` or `full` image. 
I had to manually install some dependencies to make it work: 

```
# Fix https://github.com/gitpod-io/workspace-images/issues/515 
RUN sudo apt-get update && \
    sudo apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    libgbm1 \
    wget \
    xdg-utils && \
    sudo rm -rf /var/lib/apt/lists/*
```

Any chance I can add those to any of the images? 
I am happy to provide a PR if you say where it can be added. 
I may also try to trim the list down.
