### ISSUE TITLE
Add versions of images based on Debian

### ISSUE THREAD

**Issue by tgbtwoq** [gitpod-io/workspace-images#300]
The rationale is mostly because people that like stability prefer to use Debian rather than Ubuntu.
And that this change would make people have 1 more reason to use gitpod. Which would not hurt gitpod I assume.

And make Debian specific issues more visible for Gitpod users. If they have not been fixed already.

Sorry if this has already been suggested. Or if this is the wrong place to post.

References -
1. https://github.com/gitpod-io/workspace-images/tree/master/full
2. https://github.com/gitpod-io/workspace-images/tree/master/full-vnc
3. https://github.com/gitpod-io/workspace-images/issues/53

---

Issue 53 when fixed will improve the experience for all users. Its status is not clear.
thanks

**Comment by tgbtwoq** [comment]
Does anyone else get this error message at the end of the build phase? When using debian as a base.

```
bd58e1c7fda3df64846d9ce0a size: 2416
adding Gitpod layer
..
..
..
..
..
..
..
..
..
  build failed: cannot build workspace image: The command '/bin/sh -c /var/gitpod/layer.sh     && rm -f /var/gitpod/layer.sh' returned a non-zero code: 1.
                                  Error: build failed: cannot build workspace image: The command '/bin/sh -c /var/gitpod/layer.sh     && rm -f /var/gitpod/layer.sh' returned a non-zero code: 1
```

This little snippet was pretty hard to copy in Chromium web browser, version 84. What gives?

**Comment by tgbtwoq** [comment]
renamed issue - to match with https://github.com/gitpod-io/workspace-images/issues/51

**Comment by corneliusludmann** [comment]
We are currently not planning to offer a Debian workspace image because the maintenance overhead is too high for the little benefit. However, Gitpod is open-source. Feel free to provide (and maintain) a Debian image. :+1:
