### ISSUE TITLE
Can anyone give me a Dockerfile based on Debian to test with Gitpod?

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/workspace-images#302]
Can anyone give me a Dockerfile based on Debian to test with Gitpod? 

Variants - Debian stable, and oldstable 

A minimal version.
A version with a hello world in C and C++ and Python.

Remember to ping me with my username - ret394.

---
possibly related - https://github.com/gitpod-io/workspace-images/issues/300

_Originally posted by @ret394 in https://github.com/gitpod-io/workspace-images/issues/256#issuecomment-727630742_

**Comment by corneliusludmann** [comment]
@ret394: I don't know exactly what you're asking for. You can use Debian as a workspace image simple by adding these 2 files to your repo:

**`.gitpod.Dockerfile`**
```Dockerfile
FROM debian
```

**`.gitpod.yml`**
```yaml
image:
  file: .gitpod.Dockerfile
```

That all you need. Of course, you don't have any development tools in the workspace. You need to install them by adding install commands to the Dockerfile. Does it help?

**Comment by ghuntley** [comment]
Closing this issue out due to inactivity and lack of response from the issue author.
