### ISSUE TITLE
Update composer (php package manager) to v2

### ISSUE THREAD

**Issue by strausmann** [gitpod-io/workspace-images#339]
Upgrade the Docker Image to use the latest composer version, this is currently v2.0.9

https://github.com/composer/composer

**Comment by strausmann** [comment]
Good Day @aledbf,

this is a mistake, [composer](https://getcomposer.org/) is not [docker-compose](https://docs.docker.com/compose/)...

So it seems that this issue is still open. Therefore, would you please reopen Issue #339?

Best Regards,

Bjoern

**Comment by aledbf** [comment]
@strausmann apologies. I referenced the wrong issue.

**Comment by unscripted** [comment]
I was successfully able to install Composer 2 by removing `composer \` from [line 33 of the Dockerfile](https://github.com/gitpod-io/workspace-images/blob/2f5689a36391544b3c592f987c5a6abe230f22fe/full/Dockerfile#L33) and then set `RUN brew install composer` following [line 72 of the Dockerfile](https://github.com/gitpod-io/workspace-images/blob/2f5689a36391544b3c592f987c5a6abe230f22fe/full/Dockerfile#L72).

Is this a viable solution that could be included in the full image?

**Comment by shaal** [comment]
+1

**Comment by kylos101** [comment]
Thanks for the reminder, @shaal ! :+1: I've just scheduled this as part of our dazzle v2 upgrade for this repo.
