### ISSUE TITLE
Add ninja-build to full.

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/workspace-images#357]
It's a very popular tools, used to build V8 and Node.js. Very essential to c/cpp devs. Also it's very small, around 100kb.

**Comment by jankeromnes** [comment]
Thanks for the suggestion! That's a good idea.

My only worries would be:

- What size delta would this add to `gitpod/workspace-full`? (We can assess this by starting a PR and compare the built image with master)

- Do we know for sure that projects will pickup and use our installed Ninja? (It seems to me that many projects now download a custom toolchain as part of their build process, bypassing our installed tools -- for example, I believe Chromium and Firefox both download latest Clang to build, even though Gitpod already has latest Clang installed)

**Comment by gengjiawen** [comment]
> What size delta would this add to gitpod/workspace-full?

Since docker has compression. I would expect like less than 100kb. I will start a PR later :)

> I believe Chromium and Firefox both download latest Clang to build

Yeap, they have internal toolchain. But https://github.com/bnoordhuis/v8-cmake can benefit from this. 
Also, we start using Node.js ninja build in CI, see https://github.com/nodejs/node/pull/37499.
