### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by FeixuRuins** [gitpod-io/workspace-images#363]
![image](https://user-images.githubusercontent.com/66232834/110005228-3fd24800-7ce6-11eb-9874-5caeb32d8034.png)

**Comment by akosyakov** [comment]
It looks that npm is coming together with Node.js and configured by nvm here: https://github.com/gitpod-io/workspace-images/blob/0d86f18fcb06832838d2cb77636d2c1a6a7dbe6c/full/Dockerfile#L137

**Comment by gengjiawen** [comment]
The image already using latest npm, you can see 
https://github.com/gitpod-io/workspace-images/blob/0d86f18fcb06832838d2cb77636d2c1a6a7dbe6c/full/Dockerfile#L142

`workspace-full` has npm 7. You are probably using custom docker image.

![image](https://user-images.githubusercontent.com/3759816/110264447-49182900-7ff4-11eb-9346-69e0df680d7f.png)

**Comment by FeixuRuins** [comment]
My workspace must be outdated then. I'm using https://github.com/gitpod-io/sveltejs-template, created a few weeks ago.

**Comment by smacintyre** [comment]
It causes a lot lot of problems if you mix the wrong NPM version with Node. The Node LTS should be using NPM 6.x, not 7. I've filed an issue #368 to fix this. NPM 7 should not be installed.
