### ISSUE TITLE
Wrong version of NPM installed; breaking prebuilds

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/workspace-images#368]
There is something wrong with your build process. NPM 7 keeps getting installed when it shouldn't be. This is a repeat of #358. The build tracks the Node LTS which always uses NPM 6.x. NPM 7 represent major changes. Because the installed Node has been update to 14.16.0 the previous fix in #358 we must first add a different version, the uninstall 14.16.0, and then reinstall 14.16.0. 

As long as the image is tracking the LTS, it should be using the bundled NPM -- which is version 6.

**Comment by smacintyre** [comment]
From a fresh launch / work around to fix the bad NPM install:

```sh
$ nvm ls
->     v14.16.0
default -> 14.16.0 (-> v14.16.0)
node -> stable (-> v14.16.0) (default)
stable -> 14.16 (-> v14.16.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/fermium (-> v14.16.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.0 (-> N/A)
lts/erbium -> v12.21.0 (-> N/A)
lts/fermium -> v14.16.0

$ npm -v
7.5.6

$ nvm install --lts
Installing latest LTS version.
v14.16.0 is already installed.
Now using node v14.16.0 (npm v7.5.6)

$ nvm install v14.15.0
Downloading and installing node v14.15.0...
Downloading https://nodejs.org/dist/v14.15.0/node-v14.15.0-linux-x64.tar.xz...
######################################################################################################################################################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v14.15.0 (npm v6.14.8)

$ nvm uninstall v14.16.0
Uninstalled node v14.16.0

$ nvm install --lts
Installing latest LTS version.
Downloading and installing node v14.16.0...
Local cache found: ${NVM_DIR}/.cache/bin/node-v14.16.0-linux-x64/node-v14.16.0-linux-x64.tar.xz
Checksums match! Using existing downloaded archive ${NVM_DIR}/.cache/bin/node-v14.16.0-linux-x64/node-v14.16.0-linux-x64.tar.xz
Now using node v14.16.0 (npm v6.14.11)

$ npm -v
6.14.11

$ nvm uninstall v14.15.0
Uninstalled node v14.15.0
```

As you can see, `nvm` is grabbing node from the cache so there must be another step that is overriding `nvm` and installing the wrong version of NPM. It's causes a lot of problems to mix the wrong node and npm versions.

**Comment by gengjiawen** [comment]
Npm 7 is compatible with Node.js 14, if you run into issues, you can file a bug to npm github issue page.

Currently the strategy is using latest npm, See https://github.com/gitpod-io/workspace-images/issues/363#issuecomment-792407702

**Comment by smacintyre** [comment]
@gengjiawen The image claims to follow the LTS,  Npm 7 is not part of the LTS. Npx has been rewritten and does not follow the same behaviours. Everywhere that most deploy to will be using the LTS, and that is Npm 6. The `package.json` has changed. See the whole `peerDependency` issues that are well documented with Npm 7. Until Npm 7 is part of the LTS, it should not be added here.

**Comment by gengjiawen** [comment]
Maybe gitpods do it for security reasons. But to be fair, npm lts version is 7.

https://www.npmjs.com/package/npm

![image](https://user-images.githubusercontent.com/3759816/110879378-d5d62600-8317-11eb-8482-04f887fb77b7.png)

**Comment by smacintyre** [comment]
That's not really relevant. NPM feeds into Node, so it is always ahead. Each Node LTS is matched with it's own NPM version -- which is maintained and has no security effect. Actually, given how new and untested NPM 7 is, it would be a much bigger security risk to use it now.  

The fact remains that NPM 7 breaks a lot of things and changes a lot of behaviour. It's been a source of a lot of problems in the community with many packages not being installable under NPM 7 due to the changes. This will all be resolved eventually. But that's why we follow the LTS, not the cutting edge.

**Comment by smacintyre** [comment]
Here is what is required in the dockerfile to work around the issue:

```Dockerfile
ENV OLD_NODE_VERSION=14.15.0
ENV NODE_VERSION=14.16.0
RUN bash -c ". .nvm/nvm.sh \
  && nvm install $OLD_NODE_VERSION \
  && nvm uninstall $NODE_VERSION \
  && nvm install $NODE_VERSION \
  && nvm use $NODE_VERSION \
  && nvm uninstall $OLD_NODE_VERSION \
  && npm install -g yarn \
  && nvm alias default $NODE_VERSION"
ENV PATH=/home/gitpod/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH
```

**Comment by gengjiawen** [comment]
This should work too if anyone want to get npm 6.
```docker
RUN npm i -g npm@6
```

**Comment by jankeromnes** [comment]
Thanks for reporting this problem (again)!

I can confirm that something unexpected happened in the latest `gitpod/workspace-full` build:

```
$ docker pull gitpod/workspace-full:latest
[...]
95e058e079d4: Pull complete
Digest: sha256:bb020f3cc289f978fa71c78965bd8a960651a8baf2d537844774765c9b7dcd25
Status: Downloaded newer image for gitpod/workspace-full:latest
docker.io/gitpod/workspace-full:latest

$ docker run -it --rm gitpod/workspace-full:latest /bin/bash
gitpod ~ $ . $HOME/.nvm/nvm.sh && node --version && npm --version
v14.16.0
7.5.6
```

However, when you build this minimal Dockerfile:

```Dockerfile
FROM ubuntu:20.04

RUN apt-get update -q && apt-get install -yq curl
RUN curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | PROFILE=/dev/null bash && \
    bash -c ". $HOME/.nvm/nvm.sh && nvm install --lts && node --version && npm --version"
```

you get:

```
[...]
Installing latest LTS version.
Downloading and installing node v14.16.0...
Downloading https://nodejs.org/dist/v14.16.0/node-v14.16.0-linux-x64.tar.gz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v14.16.0 (npm v6.14.11)
Creating default alias: default -> lts/* (-> v14.16.0 *)
v14.16.0
6.14.11
```

I suspect there was an upstream Node.js or NVM bug 9leading to the wrong NPM version being installed) precisely when we first built `gitpod/workspace-full:latest`, and the faulty result now lives in our cache.

We should probably invalidate the Node.js Dazzle layer and force a rebuild.

**Comment by smacintyre** [comment]
@jankeromnes Thank you!
