### ISSUE TITLE
RVM is available as Ubuntu package

### ISSUE THREAD

**Issue by orucky** [gitpod-io/workspace-images#37]
I just saw that RVM is also in the official repository, which, if works, is preferred to running an 'installer' (potential integration & security issues).

See https://github.com/rvm/ubuntu_rvm.

**Comment by deepflame** [comment]
You may think about replacing RVM by `rbenv` which is a much simpler Ruby version manager and I would argue the more popular one in the community.

If you search for `rvm rbenv` on Google you will find a lot of transition tutorials from rvm to rbenv.

There are also rbenv packages available as official Ubuntu repo:
https://packages.ubuntu.com/cosmic/rbenv

It is recommended to install ruby_build as well which downloads, builds and installs the rubies.
https://packages.ubuntu.com/cosmic/ruby-build

**Comment by deepflame** [comment]
Just had a test with rbenv and ruby-build from cosmic and have to say that it does not include newer ruby versions. Ruby-build would need to be updated (newer package  built).
So, not sure if it makes sense to use the Ubuntu package then...

**Comment by jankeromnes** [comment]
Closing this discussion due to inactivity. Please re-open it if you strongly feel we should change something about the RVM install.

**Comment by kevinhq** [comment]
Aren't you allowing to install older ruby with rvm? I always get error on installing ruby 2.3.x
