### ISSUE TITLE
apt-get fails in downstream-dockerfiles due to outdated yarn gpg-key

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/workspace-images#40]
During `docker build` of a Dockerfiles that extends `workspace-full` which uses `apt-get` I get these errors and docker-build fails.
```
Reading package lists...
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
```

To reproduce run `docker build .` on 
```
FROM gitpod/workspace-full:latest
USER root 
RUN apt-get update && apt-get install -yq htop
```

and get these warnings:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Not sure why I got a warning here and an error in my other scenario.

The cause seems to be that the yarn people have updated their GPG key (see https://github.com/yarnpkg/yarn/issues/6865) and that we store that key inside our workspace-full-image. 

Workaround: Update key before using apt-get.
```
FROM gitpod/workspace-full:latest
USER root 
RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN apt-get update && apt-get install -yq htop
```

Solution: re-build `workspace-full` image so that it includes the latest yarn GPG key.

**Comment by orucky** [comment]
I'll have a fast look in a while. The old key stopped working today (I saw it on my system.) I concluded that it should be OK in Docker builds as the key is downloaded every single time. Maybe Docker caching problem? (I.e. the key actually isn't downloaded again?)

**Comment by orucky** [comment]
OK so everything is as it should be. Can we close?

**Comment by Daniel15** [comment]
Note that a lot of Debian repos rotate their keys periodically for security reasons, so you should ensure your build system can handle that :)

Sorry for the thrash on the Yarn key, I'm going to rotate it a few months before expiry next time (which is what I meant to do this time, but forgot about it)

**Comment by meysholdt** [comment]
hey @Daniel15, thanks for saying hi. I agree that we should handle updated keys gracefully.

**Comment by orucky** [comment]
Thanks a lot for chiming in, Daniel! Could you please clarify what's the difference between having the key rotated and having it expired?

**Comment by Daniel15** [comment]
>  Could you please clarify what's the difference between having the key rotated and having it expired?

"Key rotation" is a process where you periodically change the key you use for encryption or signing. This is usually for security reasons, eg. see https://crypto.stackexchange.com/a/41814:

> for signing keys there is a concrete reason: say it takes X months of computation (expected value given your threat model) to crack a key, and you rotate your signing key every X−1 months and revoke the old one, then by the time an attacker has cracked the key, any new signatures produced by the attacker will either be A) rejected by clients because of key expiry, or B) back-dated to before the key revocation (which should also raise warning in clients).

For the Yarn Debian repository, I usually rotate the key once per year.

Usually you do this a while before the existing key expires. For example, if your key expires on 31st December 2019, you may start using a new key on 1st November 2019. This gives you enough time to test the new key and ensure the update gets out to everyone, while anything signed using the old key is still valid. You don't want to leave it to the last minute (eg. replace a key that expires tomorrow) just in case there's any issues with it.

**Comment by orucky** [comment]
OK. But from the user's perspective, is there any difference? I mean:if you rotate the key, and I run `apt-get update`, do I still get an error?

**Comment by jankeromnes** [comment]
This issue broke Gitpod's staging environment for a while, but clearing `gitpod/workspace-full` from the Docker build cache (in particular [this Docker command](https://github.com/gitpod-io/workspace-images/blob/d91385e57ed8219e2f9cf801c71b5f204ba3fe7c/full/Dockerfile#L81)) fixed it again.

Gitpod production still seems to fail, e.g. [on my Servo fork](https://gitpod.io/#https://github.com/jankeromnes/servo), which has a Dockerfile that's based on `gitpod/workspace-full-vnc` and thus on `gitpod/workspace-full` too.

**Comment by orucky** [comment]
> Gitpod production still seems to fail, e.g. on my Servo fork, which has a Dockerfile that's based on gitpod/workspace-full-vnc and thus on gitpod/workspace-full too.

`gitpod/workspace-full-vnc` is now rebuilt too, that solved your issue.

**Comment by jankeromnes** [comment]
Build fixed and new images pushed to Docker Hub (full-vnc should finish soon). Thanks everyone!

**Comment by Freitas-Mp** [comment]
hello everybody i am trying to start a project ,using yarn init  it is not working. this is error:
 **00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'init'**

**Comment by jankeromnes** [comment]
Hi @Freitas-Mp, that's unfortunate. Could you please provide the URL of your project, and describe exactly what you're doing to try `yarn init`? (E.g. 1) Open Project X in Gitpod; 2) Open a new Gitpod Terminal; 3) Type "..."; 4) etc.)
