### ISSUE TITLE
don't set `MAVEN_CONFIG`

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/workspace-images#41]
see https://github.com/gitpod-io/gitpod/issues/231

**Comment by jankeromnes** [comment]
The issue seems to indicate that this was fixed in https://github.com/gitpod-io/workspace-images/commit/d91385e57ed8219e2f9cf801c71b5f204ba3fe7c

And for what it's worth, there is currently no `MAVEN_CONFIG` in https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile
