### ISSUE TITLE
Composer is out of date on PHP image

### ISSUE THREAD

**Issue by mitchazj** [gitpod-io/workspace-images#424]
Trying out the PHP image today and got several warnings saying that composer 1 was still being used. I poked around a bit but wasn't able to find a place to update it myself on the base image.

More details here: https://getcomposer.org/upgrade/UPGRADE-2.0.md

Happy to submit a pull request if there's a correct place to :)

**Comment by sgurlt** [comment]
Subscribing to this one, +1 for updating composer to v2 :-)

**Comment by strausmann** [comment]
Please Upgrade to v2...

**Comment by mitchazj** [comment]
For anyone who isn't keen to wait for the official images, I have a fork here https://github.com/mitchazj/workspace-images-extended (happy to open a pull request!)

The docker images are
- https://hub.docker.com/r/mitchazj/workspace-full
- https://hub.docker.com/r/mitchazj/workspace-mysql

**Comment by shaal** [comment]
+1
#339 Please Upgrade to v2...

For those who want to replace current old composer and install the latest composer instead -
```
sudo rm /usr/bin/composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer
```

**Comment by codemzy** [comment]
> +1 #339 Please Upgrade to v2...
> 
> For those who want to replace current old composer and install the latest composer instead -
> 
> ```
> sudo rm /usr/bin/composer
> php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> php composer-setup.php
> php -r "unlink('composer-setup.php');"
> sudo mv composer.phar /usr/local/bin/composer
> ```

This worked for me except the last line, which I needed to change to `sudo mv composer.phar /usr/bin/composer`, thanks!

**Comment by ProgrammedMikey** [comment]
bump, have to update composer every time I stop workspace

**Comment by shaal** [comment]
According to https://github.com/gitpod-io/workspace-images/issues/339#issuecomment-1017057124, this got scheduled 2 weeks ago and will be worked on soon 🙏
