### ISSUE TITLE
[python] Consider adding `pipenv`

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/workspace-images#45]
`pipenv` is yet another layer to support individual project setups.

there are several ways to support project configurations, and `pipenv` should play nice with `pyenv`:

> Many python developers may have experienced several stages:
> - use shared system or user wide python environment
> - use virtualenv or virtualenv-wrapper
> - use pyenv
> - and now it's time to use pipenv
> 
> source: https://realpython.com/pipenv-guide/#comment-3874852797

the project config is written to [Pipfile](https://github.com/pypa/pipfile#pipfile)s.

**Comment by jankeromnes** [comment]
pipenv was installed in https://github.com/gitpod-io/workspace-images/commit/d4faa664f4e6def348a5e4b59921996a13b31f38
