### ISSUE TITLE
install the nix package manager into the base image

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/workspace-images#477]
See https://github.com/gitpod-io/template-nix for insights.

https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile is the file that would need updating.

**Comment by shism2** [comment]
``
FROM buildpack-deps:focal-curl

COPY  install-packages /usr/bin

ARG DEBIAN_FRONTEND=noninteractive
ARG DUSER=gitpod
ENV HOME=/home/$DUSER

RUN install-packages \
        bash-completion \
        sudo \
        xz-utils \
        git \
# '-l': see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
&&  useradd -l -u 33333 -G sudo -md $HOME -s /bin/bash -p $DUSER $DUSER \
# passwordless sudo for users in the 'sudo' group
&& echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && mkdir -m 0755 /etc/nix &&  chown $DUSER /etc/nix

CMD /bin/bash -l
USER $DUSER
ENV USER $DUSER
WORKDIR $HOME

RUN  touch .bash_profile && curl https://nixos.org/releases/nix/nix-2.3.15/install | sh \
&& echo '. $HOME/.nix-profile/etc/profile.d/nix.sh' >> $HOME/.bashrc \
&& mkdir -p  ~/.config/nix/ &&  printf "sandbox = false\nexperimental-features = nix-command flakes\nkeep-derivations = true\nkeep-outputs = true" > ~/.config/nix/nix.conf \
&& mkdir -p  $HOME/.config/nixpkgs && echo '{ allowUnfree = true; }' >> $HOME/.config/nixpkgs/config.nix

RUN . $HOME/.nix-profile/etc/profile.d/nix.sh \
&& nix-channel --add https://nixos.org/channels/nixpkgs-unstable  \
&& nix-channel --update \
&& nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager \
&& nix-channel --update \
&& export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH \
&& echo 'export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH' >> ~/.bashrc \
&& nix-env -iA nixpkgs.nixUnstable \
&& sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```
