### ISSUE TITLE
bashrc.d is empty on base image

### ISSUE THREAD

**Issue by telenieko** [gitpod-io/workspace-images#480]
When deriving an image from `base` you will get an error on the shell:

    ls: cannot access '/home/gitpod/.bashrc.d/*': No such file or directory

This happens because `base` has this:

https://github.com/gitpod-io/workspace-images/blob/14cf434489db719e93b62024cdea7ad557c70574/base/Dockerfile#L53-L56

But no files are created on that folder (`full` does).

Either `base` should create a dummy file there to avoid the error, or a prior test should be done to be sure there is something for `ls` to list.

**Comment by telenieko** [comment]
I guess that would be a valid solution also:

    for i in $(ls $HOME/.bashrc.d/* 2>/dev/null); do source $i; done

But that could hide errors further than the road (like a permission denied, etc)

**Comment by corneliusludmann** [comment]
Thanks for reporting!

Duplicate of https://github.com/gitpod-io/gitpod/issues/4044

PRs are very welcome!

**Comment by telenieko** [comment]
> Duplicate of [gitpod-io/gitpod#4044](https://github.com/gitpod-io/gitpod/issues/4044)

Ups. I searched on this repo for possible duplicates 😅

**Comment by corneliusludmann** [comment]
> Ups. I searched on this repo for possible duplicates

Absolutely understandable. :+1: For organizational reasons, we try to keep the issues centralized in the `gitpod-io/gitpod` repo.

**Comment by telenieko** [comment]
Closing as duplicate, https://github.com/gitpod-io/gitpod/issues/4044
