### ISSUE TITLE
Update version of Git that comes with default workspace

### ISSUE THREAD

**Issue by HonkingGoose** [gitpod-io/workspace-images#499]
I hope this report is in the right place, if not, please direct me to the correct place to report this! 😉 

## Problem

The latest version of Git is `2.33.0`.
Running `git --version` in my workspace gives: `git version 2.30.1`

## Expected behavior

I was expecting to get the latest version of Git when I start up a workspace.
I don't know what the source of the Git version is that comes with the default workspace, maybe that source is not updated yet?

## Discussion

Is there a way I can specify what version of Git I want to use, say in a `.gitpod.yml` file?
If the Gitpod team has any recommendations, please let me know! 😉 

One of the projects I'm working on will soon require Git `2.33.0` or higher to work on the code. So that's why I'm asking for a update to the Git version to `2.33.0`. 😄

**Comment by gengjiawen** [comment]
`sudo apt update && sudo apt install git -y` should fix your problem.

You can add to your init script in `.gitpod.yml` init task.

**Comment by HonkingGoose** [comment]
> `sudo apt update && sudo apt install git -y` should fix your problem.
> 
> You can add to your init script in `.gitpod.yml` init task.

Thank you for this idea! 😄

**Comment by Furisto** [comment]
We are now using git 2.35.1
