### ISSUE TITLE
feat(ci): Automating generating package dependency uupgrade PRs for stuff that's not covered by Autofix

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/workspace-images#504]
## About this issue

Currently, Autofix only covers Node Version Manager and `rustup` for automating package upgrade PRs.

The problem is either the `base`, `full` pr even language-specific ones can be outdated by the time there are some new releases behind, or even security patches aren't being applied in timely fashion.

## Possible suggestions

* Since the base image is Debian-based, maybe consider using the backports as possible in build time for tools like Git.
* For CLI tools that installed through package managers such as `npm` or `pip`, and since we're not doing any sort of version locking on Dockerfiles, maybe have an CircleCI job for checking updates and if found any, maybe update the Dockerfiles (or probably generate some base64 stuff with `date | base64 > base/.trigger-rebuild`).
* For language version managers or languages don't have official (or even an active community-maintained) version managers yet, maybe expand Autofix suppory more wider.

**Comment by kylos101** [comment]
Hi there, [autofix covers more now](https://github.com/autofix-dev/autofix#types-of-bugs-that-can-be-fixed). Please feel free to comment or reopen if it is still an issue? :pray:
