### ISSUE TITLE
Uploading file from VM

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/workspace-images#509]
I have a file in the VM. (/home/gitpod/.crawl/saves/mteam88.cs). I would like to export it to my computer that is running gitpod. (It would also be helpful if I could save the entire VM). Later I would like to able to import it back to the same directory. How would I do this? Please give a simple answer I am new to Linux and VMs.

**Comment by mteam88** [comment]
It is possible that I am doing something wrong... I am using the terminal with the workspace code directly from gitpod...

**Comment by Furisto** [comment]
@mteam88 You could open the folder like this in vscode `code /home/gitpod/.crawl/saves/`. Then in the file explorer right click the file and select `Download...`

In the same vein you can also select `Upload...` to upload files.

**Comment by Furisto** [comment]
Closing, but feel free to reach out again if these instructions do not work for you.

**Comment by mteam88** [comment]
> @mteam88 You could open the folder like this in vscode `code /home/gitpod/.crawl/saves/`. Then in the file explorer right click the file and select `Download...`
> 
> In the same vein you can also select `Upload...` to upload files.

A yes. I saw your post @Furisto I wanted a script to do this, but I have figured it out using what you did, just in command line form.
