### ISSUE TITLE
[Proposal] Define a modular, hierarchial structure for stacks

### ISSUE THREAD

**Issue by sr229** [gitpod-io/workspace-images#51]
One thing I've noticed is `workspace-full` and `workspace-full-vnc` is a very giant monolithic image. 

However, in Eclipse Che, there is a set defined hierarchy of images, starting with the root of the hierarchy is the base images, where it could be `stack-base:debian` or `stack-base:ubuntu`.

I believe in Gitpod we can do the same, where we slim out the `workspace-full` and `workspace-full-vnc` to only include some basic build dependencies, and by `FROM` directives, can spawn a deriverative stack from a simple stack. This allows a much more maintainable image and a smaller base stack size

**Comment by sr229** [comment]
This is how essentially this looks like in Eclipse Che for their stacks

![image](https://user-images.githubusercontent.com/14976516/51681456-9822c000-201f-11e9-8e9c-71a6e491e235.png)

**Comment by jankeromnes** [comment]
Thank you for this interesting proposal! I agree that our Docker image tree needs to be improved.

A modular structure seems indeed "cleaner" from a theoretical standpoint, yet we'd be shifting complexity from our single monolithic image over to numerous small language stacks that would need to be maintained separately.

From an operational perspective, I quite like the simplicity of having mostly only one image to maintain, and I don't think that having a large base image is that big of a problem. In a similar project, [janitor.technology](https://janitor.technology), we went even further by adding anything that could be useful to at least 2 projects into our base image, [ubuntu-dev](https://github.com/JanitorTechnology/dockerfiles/blob/master/ubuntu-dev/ubuntu-dev.dockerfile). That way, many projects also share the same base image, thus saving disk space & bandwidth thanks to copy-on-write.

I'm not fundamentally opposed to modular images, but what would be the concrete benefits of having smaller base images?

**Comment by sr229** [comment]
@jankeromnes Small base images tends to have few layers and very fast pull times - which sometimes has benefits, since:

- We're pulling already some things we need such as `build-essential` preinstalled, etc.

- We can just extend it further via another stack, which adds few layers into a probaby 3-4 layer image.

**Comment by jankeromnes** [comment]
Thank you for these details. It would be interesting to measure Gitpod workspace start-up times again, and see if image pull times could/should be made faster with modular images.

Related to this change, I'd like to migrate our Docker build infrastructure from pure Docker Hub over to CircleCI (still pushing to Docker Hub in the end). This would allow us to describe the dependencies between our images declaratively in a [config file](https://github.com/JanitorTechnology/dockerfiles/blob/master/.circleci/config.yml), adding more visibility to our tree and help think about potential changes. (Also, CircleCI is equally free, yet it builds much faster than Docker Hub, and works for cross-repo pull requests).

**Comment by meysholdt** [comment]
hey @sr229, thank you for this suggestion. I very much like the idea of modularity and having a (langage-indenpendent?) base image. 

I also agree that workspace-full is inconveniently large. Besides decomposition, there is also room for optimization (#53).

The idea of language packs is intriguing and it would be great if they could be freely combined. I'm not sure yet on how to do this within a single docker image since every docker image can only have exactly one base image.

**Comment by svenefftinge** [comment]
One reason we have the one-size-fits all image is that it works for many not yet gitpodified projects out there. If we had different images for different languages, we would need to detect and guess the right image. The user doesn't see the docker pull times as the images are cached.

**Comment by sr229** [comment]
I think we can always assume the language stack based on the project directory structure or the package manifest @svenefftinge, but I believe that's a ton more load than it needs to be.

**Comment by sr229** [comment]
> One reason we have the one-size-fits all image is that it works for many not yet gitpodified projects out there. If we had different images for different languages, we would need to detect and guess the right image. The user doesn't see the docker pull times as the images are cached.

I think another problem Gitpod also has is that we don't allow manual package installations. Hence people cannot mix and match on the fly. If we allow package installs there'll be more adoption and would allow people to write their own stacks when they finally grow tired of doing the same thing over and over.

**Comment by sr229** [comment]
> One reason we have the one-size-fits all image is that it works for many not yet gitpodified projects out there. If we had different images for different languages, we would need to detect and guess the right image. The user doesn't see the docker pull times as the images are cached.

I think another problem Gitpod also has is that we don't allow manual package installations. Hence people cannot mix and match on the fly. If we allow package installs there'll be more adoption and would allow people to write their own stacks when they finally grow tired of doing the same thing over and over.

**Comment by atduarte** [comment]
A lot has changed since this discussion, and several improvements were made. I will go ahead and close this, but feel free to reopen in case you feel the issue remains.
