### ISSUE TITLE
README insufficient

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/workspace-images#510]
Add a simple guide (or link to) a way to actually use one of the images in gitpod. Directions would really make it a better tool. Please advise if there is an existing tutorial.

**Comment by kylos101** [comment]
Hi @mteam88 , I'm late to the party, but, this is a great idea. I think linking to [this page would be best](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile), as it contains an example. I'll close the PR for now, but keep the issue open so we can add a link. You have a nice day. :smile:
