### ISSUE TITLE
Make Puppeteer work in default workspace

### ISSUE THREAD

**Issue by DanielHabenicht** [gitpod-io/workspace-images#515]
Coming here from: https://community.gitpod.io/t/using-puppeteer-libnss3-no-file-or-directory-issue-on-gitpod/1762?u=danielhabenicht

Where should I implement the solution? 
In the `full` or `base` image?

**Comment by gengjiawen** [comment]
https://github.com/gitpod-io/workspace-images/pull/471/ should do.
