### ISSUE TITLE
Optimize Image Layers in workspace-full

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/workspace-images#53]
when running [dive](https://github.com/wagoodman/dive)` gitpod/workspace-full:latest` I get

![image](https://user-images.githubusercontent.com/239422/51690028-23885b00-1ff8-11e9-967a-e69fdaa4a0ff.png)

Notable here:
1. dive says the layers hold more than 800MB redundant data. This means files that are overwritten in subsequent layers.
2. I see (1) for `git` and `gcc`. I assume some layer installs them again even though they were installed already.
3. I see caches from `go`, `npm`, `pip`, etc. not being cleaned up and fully going into the layer. Maybe we can delete them. example:

![image](https://user-images.githubusercontent.com/239422/51690411-eb354c80-1ff8-11e9-9ebe-fd2161f98042.png)

**Comment by meysholdt** [comment]
The current state of the beast:

![image](https://user-images.githubusercontent.com/239422/57082165-7c9e1400-6cf6-11e9-910f-ef4fdc41bd73.png)

**Comment by jankeromnes** [comment]
@meysholdt Have image layers been optimized? What remains to be done to resolve this issue? 🙂

**Comment by aledbf** [comment]
@jankeromnes can we close this now?

**Comment by jankeromnes** [comment]
@aledbf Yes indeed, thanks!
