### ISSUE TITLE
Dotnet broken

### ISSUE THREAD

**Issue by chuck-alt-delete** [gitpod-io/workspace-images#537]
Dotnet appears to be broken all around gitpod. For example, when running dotnet run from the template repo, here is the output:

```
/home/gitpod/dotnet/sdk/5.0.205/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6004: The specified task executable location "/run/containerd/io.containerd.runtime.v2.task/k8s.io/2c519a5f761011a81629823616e6a2636fe27f4db0de9d7631e8aa1fc52b56d6/rootfs/home/gitpod/dotnet/dotnet" is invalid. [/workspace/template-dotnet-core-cli-csharp/dotnetcore.csproj]
```

It’s not just the template repo, though. As far as I can tell, even otherwise working dotnet projects will not run in gitpod.

**Comment by ghuntley** [comment]
Tracking at https://github.com/gitpod-io/gitpod/issues/6460
