### ISSUE TITLE
Docker error when running intellij idea on gitpod

### ISSUE THREAD

**Issue by ItCameFr0mMars** [gitpod-io/workspace-images#565]
When I run this repo: https://github.com/gitpod-io/template-jetbrains-intellij-idea
I get the error: `docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.`

This repo fixes it, however, and also updates the version of intellij. I recommend that you update it. 
https://github.com/buggtb/template-jetbrains-intellij-idea/tree/patch-1

**Comment by axonasif** [comment]
Hi @ItCameFr0mMars, it was updated.
