### ISSUE TITLE
Encourage community contributions

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#572]
Update the readme.
- [x] Link to contribution guide, remove Circle CI reference, add badges for main and promotion actions

Update the contribution guide.
- [x] How do I develop and test in Gitpod
- [ ] Add best practices (path, user, and apt keys)
- [x] Set expectations for Gitpod workspace (build of chunks initially takes 1h)
- [x] Set expectations for when you push to a PR (a Github Actions builds and tests, chunks are cached, takes about 20m)
- <del> [ ] How to use the launch.json configuration (if you're debugging an issue with dazzle source code, cloned into the workspace-images repo) </del>

**Comment by princerachit** [comment]
>How to use the launch.json configuration (if you're debugging an issue with dazzle source code, cloned into the workspace-images repo)

I don't think this should be part of the documentation. If there is a bug in dazzle source code then we should fix it separately
