### ISSUE TITLE
Release dazzle v2 for workspace-full

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#574]
Swap to v2 image for workspace-full
- [x] move v1 image content to a legacy sub-folder
- [x] move v2 image content to the root
- [x] remove CircleCI
- [x] Resolve the conflict for full/Dockerfile
- [x] Confirm test success for `tool-postgresql` [in this action](https://github.com/gitpod-io/workspace-images/actions/runs/1737842982), potentially fixed in 645753afa6d043e244c97dc4378b8bd7100177f6 
- [x] Investigate nature of Python issues with full image causing minor changes in dev image - is there a solve in the full we can do?
- [x] Squash #593 to less commits :wink: 
- [x] measure usage of new workspace-full to assess proper dog fooding was done (SQL query in DB)
- [x] dog food internally, and handle issues with new workspace-full
- [x] update workspace-full repo with a "escape hatch" text, to help users who have trouble with new image
- [ ] push new workspace-full to Docker Hub with latest tag

**Comment by princerachit** [comment]
@kylos101 Below are the image statuses. Although I have added a "escape hatch" text, to help users who have trouble with new image" in the dockerhub repo I have additionally updated the repo readme with this information.

## Tagged `latest` to `legacy-dazzle-v1`
gitpod/workspace-full
gitpod/workspace-dotnet-lts-vnc
gitpod/workspace-dotnet-vnc
gitpod/workspace-wasm
gitpod/workspace-flutter
gitpod/workspace-dotnet
gitpod/workspace-mysql
gitpod/workspace-dotnet-lts
gitpod/workspace-postgres
gitpod/workspace-mongodb
gitpod/workspace-base
gitpod/workspace-gecko


## Not tagged

### Issue while tagging
gitpod/workspace-full-vnc ---- Not able to push
gitpod/workspace-images-dazzle --- this doesn't look like actual image rather a collection of chunks

### Old images, No publish in past month
gitpod/workspace-python-tk-vnc
gitpod/workspace-python-tk
gitpod/workspace-thin
gitpod/workspace-webassembly
gitpod/workspace-firefox
gitpod/workspace-full-dazzle
gitpod/workspace-mysql-8
gitpod/workspace-rethinkdb

**Comment by princerachit** [comment]
I can see there have been 114 ws created with the dogfood image. I checked the workspaceImage of my running ws and used that image name to get the count. 

```
	"SELECT Count(*) FROM d_b_workspace_instance where workspaceImage = 'eu.gcr.io/gitpod-dev/workspace-images:714ed1daaa84f51b16f375cb8750d2ab6b9dd0ee13d9bfb6e905c8a677a88313';"
```

output
```
[
  {
    "Count_28__2a__29_": "114"
  }
]
```

**Comment by princerachit** [comment]
Update: I checked for all the workspace created by the two images we used for dog fooding (initial one was changed due to a PR which got fixed [here](https://github.com/gitpod-io/gitpod/pull/7742)).

## Query

```
SELECT count(*) FROM d_b_workspace_instance where workspaceImage = 'eu.gcr.io/gitpod-dev/workspace-images:0d20f98ed38eede45642387265a05ef42a64f15f10d67aa878567fc96a9b02b4' or workspaceImage = 'eu.gcr.io/gitpod-dev/workspace-images:714ed1daaa84f51b16f375cb8750d2ab6b9dd0ee13d9bfb6e905c8a677a88313';
```

## Result

```
256
```

**Comment by princerachit** [comment]
Since 256 workspaces is enough to asses the reliability of image and we have not seen any issues raised by gitpod team, I have marked dogfooding and fixing issues with workspace-full as completed.

@kylos101 please review the changes (I have squashed the commits to small set of commits) and README update.
