### ISSUE TITLE
Improve speed of dazzle build and combine in Actions

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#575]
Without caching, each run can take 45m-1h 15m.

**Comment by kylos101** [comment]
Hey @princerachit , I updated the approvers for the "production" environment, which we're using now with the `ws-team/dazzle-rewrite` branch. If that Action gets triggered and you want it to run, you'll have to approve it from the Actions menu.

It takes a while to run (even with the cache, I feel like it should be quicker than 49m for back to back runs.

Aside from the time it takes to finish, can you think of anything else that we might need to fix or add to the Github Actions for pull requests?

What about the main workflow?

**Comment by princerachit** [comment]
>Hey @princerachit , I updated the approvers for the "production" environment, which we're using now with the ws-team/dazzle-rewrite branch. If that Action gets triggered and you want it to run, you'll have to approve it from the Actions menu.

👋🏾 @kylos101 thanks for the work.

> It takes a while to run (even with the cache, I feel like it should be quicker than 49m for back to back runs.

I am trying to figure out what is wrong with cache. I have pushed a [commit](https://github.com/gitpod-io/workspace-images/commit/ce3619e19fcf54034547dccb2921e9533b2edfaf) to [the PR](https://github.com/gitpod-io/workspace-images/pull/593) to test out a few things.


>Aside from the time it takes to finish, can you think of anything else that we might need to fix or add to the Github Actions for pull requests? What about the main workflow?


I cannot think of anything else other than changing a few lines of codes here and there when we migrate from `dazzle-rewrite` dir to the root of the project.

**Comment by princerachit** [comment]
@kylos101 you suggested a week back that we instead use GAR directly while building the image because of the limit on the cache size. I would like to explore that option as we will continue to grow workspace-images and will probably run out of space at some point in time.
