### ISSUE TITLE
Update Docker Compose to Version 2

### ISSUE THREAD

**Issue by chuck-confluent** [gitpod-io/workspace-images#577]
See https://docs.docker.com/compose/cli-command/

**Comment by utam0k** [comment]
@chuck-confluent Hi, thanks for raising this issue. Now you can available docker compose version2.
```console
gitpod /workspace/template-typescript-node-tabnine (master) $ docker-compose version
Docker Compose version v2.2.2
```

BTW docker-compose is installed directly in the workspace, not including the workspace image.
https://github.com/gitpod-io/gitpod/blob/ba168ed329501b89f70c6d5a2628d9b1c42573c0/components/docker-up/docker-up/main.go#L274

**Comment by chuck-confluent** [comment]
The `docker-compose` version is updated, but the `docker` CLI is not aware of it. As far as I can tell, the `docker compose` command is still showing that the compose subcommand does not exist. In other words, `docker-compose` works as intended, but not `docker compose`. The reason this matters is because I think the recommendation from Docker is shifting to standardize on `docker compose` rather than `docker-compose`.

**Comment by utam0k** [comment]
@chuck-confluent I'm sorry, I misunderstand this issue. We don't specify any particular version, but we use the latest version that fits our OS.
https://github.com/gitpod-io/workspace-images/blob/be4abbb8fb234153a743b2f09435fee71c00e0aa/chunks/tool-docker/Dockerfile#L10-L14

**Comment by Furisto** [comment]
We could symlink docker-compose into /usr/local/lib/docker/cli-plugins. That way it can be found by the docker cli and the command is available.

**Comment by chuck-confluent** [comment]
That would be cheating! Haha

No, the point is really this: https://docs.docker.com/compose/cli-command/#context-of-docker-compose-evolution

`docker-compose` CLI version 2 is I think not the same as "Compose V2" that those docs are talking about. "Compose" itself has become a specification, and the specification is now V2. The `compose` subcommand of the `docker` CLI is guaranteed to align with the "Compose V2" because it taps into the same Go binaries that define the spec, whereas the `docker-compose` CLI is a step removed and therefore more vulnerable to drift. The idea is that `docker compose up` will be able to integrate with any "Compose V2" compliant service, like AWS ECS, or Google Cloud Run. The `docker-compose` CLI can't guarantee that indefinitely. It hasn't been announced, but I suspect `docker-compose` will be deprecated at some point. Since Gitpod is a somewhat controlled environment, y'all can be opinionated about things like this and opt to standardize on `docker compose` sooner rather than later.
