### ISSUE TITLE
Setup pre-commit as part of Github actions

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#594]
Let's use [pre-commit](https://pre-commit.com/) to check code...pre-commit. It is capable of checking [these things](https://pre-commit.com/hooks.html), which are called hooks, but are really more like plugins.

Refer to [this as an example](https://github.com/gitpod-io/gitpod/blob/main/.pre-commit-config.yaml).

**Comment by kylos101** [comment]
Resolved and working in https://github.com/gitpod-io/workspace-images/actions/runs/1655551113

**Comment by kylos101** [comment]
Hey @princerachit , may I ask you to review 8eb547e995391149aa08947eb3785a4c4fbcb154? 
If you think it is okay, feel free to close this issue. Thank you, sir!

**Comment by princerachit** [comment]
Looks good to me!
