### ISSUE TITLE
Install newer versions of python in gitpod/workspace-full image

### ISSUE THREAD

**Issue by dsbowen** [gitpod-io/workspace-images#600]
## Describe the behaviour you'd like

I'd like to be able to switch to a newer python version using pyenv without installing it myself.

## Describe alternatives you've considered

Custom Dockerfile or installing in the init step, but both of these solutions 1) require more work from your users, 2) make the prebuild take longer. In my experience, the init solution adds 1-2 minutes to the prebuild and the Dockerfile solution adds 5-15 minutes.

## Additional context

This should be as easy as adding

```
RUN pyenv install 3.9.7 && pyenv install <some other newer version>
```

to the gitpod/workspace-full Dockerfile.

To get even more up-to-date versions, I'd recommend installing pyenv using [Github checkout](https://github.com/pyenv/pyenv#basic-github-checkout) instead of the pyenv installer. So, replace

```
RUN curl -fsSL https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
```

with

```
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```

## How to implement

Add dazzle variants for Python 3.6, 3.7, 3.8, 3.9, and 3.10, and upload distinct workspace-images for each variant. This would be similar to what we do now with Java 11/17, and Node/Node LTS, except we'd have 5 Python variants.

**Comment by kylos101** [comment]
Hey @dsbowen , as a heads up, I transferred this issue to our [workspace-images](https://github.com/gitpod-io/workspace-images) repo. This is where we manage images like `workspace-full`. Thank you for the issue!

**Comment by kylos101** [comment]
Hi @dsbowen which versions are you thinking that would be beneficial? I am thinking it would be best to limit versions to [ones that are still in support, plus the most recent not supported one](https://www.python.org/downloads/) (3.6, 3.7, 3.8, 3.9, and 3.10). What do you think?

As background, [for Node](https://nodejs.org/en/), we provide two [variants](https://github.com/gitpod-io/workspace-images/blob/master/chunks/lang-node/chunk.yaml) (LTS/16 and latest/17), and [combine](https://github.com/gitpod-io/workspace-images/blob/master/dazzle.yaml#L43-L52) them into images. The end result images are:
* https://hub.docker.com/r/gitpod/workspace-node
* https://hub.docker.com/r/gitpod/workspace-node-lts

We haven't created [Python variants yet](https://github.com/gitpod-io/workspace-images/tree/master/chunks/lang-python). 

When we do, the end result will be specific images, like:
* https://hub.docker.com/r/gitpod/workspace-java-11
* https://hub.docker.com/r/gitpod/workspace-java-17

Such as (doesn't exist yet): https://hub.docker.com/r/gitpod/workspace-python-3-7

**Comment by dsbowen** [comment]
> Hi @dsbowen which versions are you thinking that would be beneficial? I am thinking it would be best to limit versions to [ones that are still in support, plus the most recent not supported one](https://www.python.org/downloads/) (3.6, 3.7, 3.8, 3.9, and 3.10). What do you think?

Exactly, the latest versions of 3.6-3.10 would be perfect. Thank you!
