### ISSUE TITLE
Python Tk+noVNC help

### ISSUE THREAD

**Issue by im-coder-lg** [gitpod-io/workspace-images#609]
### Bug description

This is not a bug report, this is a question. I couldn't open a question in the forums so I had no choice :(
So, I and a few friends on GitHub are working on [a project](https://github.com/sumeshir26/TimerX)(Python, Tk and some themings and plugins) and I recently made a PR adding a website based on Node.js. Since we use Tkinter(along with Sun Valley Tcl), we couldn't enable the app, but after finding a Python Tk+noVNC image on Gitpod, I actually tested it. The app doesn't fail but noVNC doesn't work.

### Steps to reproduce

Just hit this link: https://gitpod.io/#https://github.com/sumeshir26/TimerX
Doesn't open noVNC, the tab works but you'll experience a loop of loading.

### Expected behavior

It's just supposed to start noVNC like in the `workspace-full-vnc` image.

### Example repository

https://github.com/sumeshir26/TimerX
That's the best I got.

### Anything else?

If you have discarded the image and have another suggestion like using the `workspace-full-vnc` image customized with Tkinter, please do tell us here.
Also /ping @sumeshir26 you _must_ know this, sorry for the disturbance though.

**Comment by axonasif** [comment]
Hi @im-coder-lg, you can try adding `sudo apt-get install -q tk-dev` at [here](https://github.com/sumeshir26/TimerX/blob/9ec9dba7dc895c6a1ebe26ad212ccee3507fd81d/.gitpod.Dockerfile#L3). I'm not sure if this will work. @jankeromnes told to add before PYENV installation [here](https://community.gitpod.io/t/how-to-install-tk-and-tkinter-gitpod/274/8)

**Comment by im-coder-lg** [comment]
Yeah I know that but how can you add that image to your Dockerfile?

**Comment by axonasif** [comment]
> Yeah I know that but how can you add that image to your Dockerfile?

use `FROM workspace-full-vnc:latest` in your dockerfile at [here](https://github.com/sumeshir26/TimerX/blob/9ec9dba7dc895c6a1ebe26ad212ccee3507fd81d/.gitpod.Dockerfile#L2)

And BTW...
> I couldn't open a question in the forums so I had no choice :(
There is an active discord server at the moment ;)
https://www.gitpod.io/chat

**Comment by im-coder-lg** [comment]
I want to publish this on Docker Hub but Docker Hub is asking me to pay which I don't want to do, considering that I am a teenager. So am I supposed to get the _entire_ code and put it there? If yes then how? Can you atleast try making a PR to the `gp-pytk-novnc` branch or something similar? I'll merge those changes(I can in this case since it's going to another branch than the main branch) and test them.

**Comment by im-coder-lg** [comment]
> There is an active discord server at the moment ;)

I don't have an account at Discord and I won't make one for the time being. Why not use GitHub Discussions too? That's be kinda easy right?

**Comment by im-coder-lg** [comment]
> use `FROM workspace-full-vnc:latest` in your dockerfile at here

Yeah but then you install Tk _after_ pyenv, those codes would execute first right? I want to make it simplistic, kinda exclusive. When I tried using the code found on this repo, it gave me a solid fail since it couldn't find the files.

**Comment by axonasif** [comment]
> The app doesn't fail but noVNC doesn't work.

I just tried it on my fork and noVNC is working without any issues.
![Screenshot_20220101-200909~2](https://user-images.githubusercontent.com/39482679/147852511-f411e6b3-a3d2-4ff8-8bb5-e6eded325e66.png)

**Comment by axonasif** [comment]
> Yeah but then you install Tk _after_ pyenv, those codes would execute first right?

Yeah, `workspace-full-vnc` comes first.

**Comment by axonasif** [comment]
> > There is an active discord server at the moment ;)
> 
> I don't have an account at Discord and I won't make one for the time being. Why not use GitHub Discussions too? That's be kinda easy right?

I wasn't suggesting that we should continue this on Discord, that was just to let you know that the forum is abandoned now and discord is so far the only medium officially 😄

**Comment by im-coder-lg** [comment]
Ok, maybe it's my Brave Browser.

**Comment by im-coder-lg** [comment]
Yeah it seems to work on my Android. But do you have any solution for Gitpod skipping the `init:` command? It happens to me so any ideas?

**Comment by im-coder-lg** [comment]
Other than that, `before:` and `command:` work except `init:`. Maybe you'd have noticed Playsound missing but I added it to the `init:` command, same to Docusaurus, my website generator missing right?

**Comment by axonasif** [comment]
> Yeah it seems to work on my Android. But do you have any solution for Gitpod skipping the `init:` command? It happens to me so any ideas?

I see that you are running `pip` command in your `init:`

You need to install those dependencies from either `before/command:` task or from Dockerfile without requirements.txt as python path is under `/home/gitpod` but not `/workspace`. Init changes do not persist anywhere other than `/workspace`.

**Comment by im-coder-lg** [comment]
Yeah but the repo's under workspace, then why doesn't it work?

**Comment by axonasif** [comment]
> Yeah but the repo's under workspace, then why doesn't it work?

As I said in my previous reply, pip modules are installed somewhere within `/home/gitpod` AFAIK but not `/workspace`

**Comment by im-coder-lg** [comment]
@jankeromnes can you try helping me with the Dockerfile? @axonasif's answer is satisfactory(thanks for the answer too @axonasif), but my problem is that I want it to work flawlessly and I don't want any more codes. The ones I get from here fail.
If you don't understand, here's what I mean:
I need a Dockerfile that has noVNC, Tkinter and Node.js since we are working on a GUI app. The Node part is for the website.
I have tried copying the code I found here but to no avail.
Can you help me with a custom Dockerfile?

**Comment by axonasif** [comment]
@im-coder-lg , I'm happy to help with a custom dockerfile if you need but could you please give me a hint of how should I test the tkinter installation?

**Comment by im-coder-lg** [comment]
Oh, wow! I'd love some help from you, I deffo need it now!

**Comment by im-coder-lg** [comment]
Have you forked the repo? Maybe this can be continued there, I recommend that you open an issue at the repo.

**Comment by im-coder-lg** [comment]
Linking the repo from my PR!

**Comment by im-coder-lg** [comment]
> could you please give me a hint of how should I test the Tkinter installation?

I don't understand, what do you actually mean? If you are asking for a simple Tkinter test, try this:
```python
import tkinter as tk

root = tk.Tk()
root.title('Test')
root.geometry('300x210')

root.mainloop()
```
That would work nicely. PS: Add noVNC!

**Comment by jankeromnes** [comment]
Hi @im-coder-lg! Sorry for the late response.

I've looked into this previously, and I found out that for `tk` to work, you need to install it _before_ Pyenv itself is installed.

As soon as Pyenv is installed (without tk), I found absolutely no way to make `tk` work.

That's why I opened this PR: https://github.com/gitpod-io/workspace-images/pull/146 (in order to run `sudo apt-get install -yq tk-dev` _before_ the `pyenv-installer` is run).

However, this PR could not be merged, because we don't want to install `tk-dev` for every user of `workspace-full`, because installing `tk-dev` also installs `libx11` and the entire Linux graphical stack, making `workspace-full` as heavy as `workspace-full-vnc` (even though most users of `workspace-full` don't actually need a graphical stack).

So, to summarize, if you want both `tk` and noVNC, I suggest you do the following:
1. Copy this Dockerfile https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile into your repository
2. Remove any parts that you don't need (e.g. you can remove the PHP block, the Homebrew block, the Ruby block, etc)
3. In the Python block, add `sudo apt-get install -yq tk-dev` _before_ the `pyenv-installer` is executed, just like in my old PR: https://github.com/gitpod-io/workspace-images/pull/146/files
4. Also, copy every line of https://github.com/gitpod-io/workspace-images/blob/master/full-vnc/Dockerfile (except the `FROM` line), and paste them at the bottom of your Dockerfile

You'll also need to copy these files over to your repository, next to your Dockerfile:
- https://github.com/gitpod-io/workspace-images/blob/master/full-vnc/novnc-index.html
- https://github.com/gitpod-io/workspace-images/blob/master/full-vnc/start-vnc-session.sh
- and maybe https://github.com/gitpod-io/workspace-images/blob/master/full/nvm-lazy.sh if you decide to keep the Node.js block

Sorry that this is so convoluted. I believe this is the only way to get `tk` to work with Pyenv. Please let me know if you run into problems while trying this.

**Comment by im-coder-lg** [comment]
I have tried that but it doesn't recognise the file. Can you try making a PR at our repo to fix that?

**Comment by axonasif** [comment]
I had made the dockerfile and the build was running but my workspace was timed out, now waiting on it's stopping stage 😅

**Comment by im-coder-lg** [comment]
It worked?

**Comment by im-coder-lg** [comment]
Also, how are you editing? I don't see your fork.

**Comment by axonasif** [comment]
@im-coder-lg try using this image on your `.gitpod.yml`
```yml
image: axonasif/gitpod-workspace-images:tkinter_vnc_full
```

Let me know if everything is working as expected.

**Comment by im-coder-lg** [comment]
It's stuck at `Connecting to workspace logs...`, where is your dockerfile? I just want to see it, if this doesn't work, you open a PR for this, just so you get the right credits.

**Comment by axonasif** [comment]
> It's stuck at `Connecting to workspace logs...`, where is your dockerfile? I just want to see it, if this doesn't work, you open a PR for this, just so you get the right credits.

Please be patient, the image builder can be busy sometimes and hence the delay, it should eventually build the image for you and you're good to go!

**Comment by im-coder-lg** [comment]
@jankeromnes @axonasif's Dockerfile works. I think it might be easier if that image is over here. It works flawlessly, except I think people will have to install their node versions via `nvm`. It currently sits on 12.0, not 14/16/17.

**Comment by axonasif** [comment]
Closing this.
