### ISSUE TITLE
Research hadolint-docker errors and warnings

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#614]
Do the below errors exist outside of the dazzle-rewrite folder? 
* If yes, that means they're existing in the wild now, please create a new issue, but don't assign it to this epic.
* If no, we must fix these errors, as they were introduced by us as part of the rewrite effort. Create a new issue and assign it to this epic.

[The linter configuration is located here.](https://github.com/gitpod-io/workspace-images/blob/ws-team/dazzle-rewrite/.pre-commit-config.yaml#L25-L29). Once the errors have been resolved, we should be able to uncomment the precommit hook so that **hadolint-docker** runs with every build.

**Errors**

dazzle-rewrite/chunks/tool-postgresql/Dockerfile:5 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/lang-rust/Dockerfile:6 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/lang-rust/Dockerfile:21 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/lang-python/Dockerfile:5 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/lang-python/Dockerfile:9 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/base/Dockerfile:56 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/base/Dockerfile:62 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/tool-vnc/Dockerfile:5 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/tool-brew/Dockerfile:13 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/lang-go/Dockerfile:12 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:8 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root

**Warnings**

dazzle-rewrite/chunks/tool-postgresql/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-rust/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-rust/Dockerfile:6 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/lang-python/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-python/Dockerfile:9 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/lang-python/Dockerfile:9 DL3013 warning: Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>` or `pip install --requirement <requirements file>`
dazzle-rewrite/base/Dockerfile:8 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/tool-vnc/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/tool-vnc/Dockerfile:32 DL3002 warning: Last USER should not be root
dazzle-rewrite/chunks/tool-nginx/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/tool-nginx/Dockerfile:4 DL3002 warning: Last USER should not be root
dazzle-rewrite/chunks/lang-clojure/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-clojure/Dockerfile:4 DL3002 warning: Last USER should not be root
dazzle-rewrite/chunks/tool-brew/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-node/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-node/Dockerfile:9 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/lang-go/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-go/Dockerfile:12 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/lang-c/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-c/Dockerfile:4 DL3002 warning: Last USER should not be root
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:4 DL3002 warning: Last USER should not be root
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:8 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:8 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/lang-java/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-java/Dockerfile:8 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/tool-nix/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/tool-nix/Dockerfile:22 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/lang-ruby/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/lang-ruby/Dockerfile:8 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
dazzle-rewrite/chunks/tool-docker/Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
dazzle-rewrite/chunks/tool-docker/Dockerfile:4 DL3002 warning: Last USER should not be root
dazzle-rewrite/chunks/tool-docker/Dockerfile:12 SC2046 warning: Quote this to prevent word splitting.
dazzle-rewrite/chunks/tool-docker/Dockerfile:15 SC2046 warning: Quote this to prevent word splitting.
dazzle-rewrite/chunks/tool-docker/Dockerfile:19 DL3027 warning: Do not use apt as it is meant to be a end-user tool, use apt-get or apt-cache instead

**Informational** 

dazzle-rewrite/chunks/lang-python/Dockerfile:9 SC2016 info: Expressions don't expand in single quotes, use double quotes for that.
dazzle-rewrite/chunks/tool-vnc/Dockerfile:30 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
dazzle-rewrite/chunks/lang-clojure/Dockerfile:7 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:8 DL3009 info: Delete the apt-get lists after installing something
dazzle-rewrite/chunks/tool-tailscale/Dockerfile:8 DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
dazzle-rewrite/chunks/tool-nix/Dockerfile:11 SC2086 info: Double quote to prevent globbing and word splitting.
dazzle-rewrite/chunks/tool-nix/Dockerfile:24 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
dazzle-rewrite/chunks/tool-nix/Dockerfile:25 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
dazzle-rewrite/chunks/tool-nix/Dockerfile:28 SC1091 info: Not following: File not included in mock.
dazzle-rewrite/chunks/lang-ruby/Dockerfile:8 SC2016 info: Expressions don't expand in single quotes, use double quotes for that.
dazzle-rewrite/chunks/lang-ruby/Dockerfile:19 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
dazzle-rewrite/chunks/tool-docker/Dockerfile:12 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
dazzle-rewrite/chunks/tool-docker/Dockerfile:15 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.

**Comment by princerachit** [comment]
Hey @kylos101 the linter config link is broken can you share reference that you used to create that file?

**Comment by princerachit** [comment]
I can see similar errors and warnings exist for legacy images too. 

```bash
$ docker run -v /workspace/workspace-images/legacy:/myvol --rm -i hadolint/hadolint hadolint /myvol/full/Dockerfile
```

<details>
<summary>Click to toggle the output form above command</summary>

```console
Unable to find image 'hadolint/hadolint:latest' locally
latest: Pulling from hadolint/hadolint
d0727728368a: Pull complete 
Digest: sha256:1b47f3192d2c69c622863b84d5cccbfa0c1fac9022bfc297aa931e6d44e51608
Status: Downloaded newer image for hadolint/hadolint:latest
/myvol/full/Dockerfile:2 DL3007 warning: Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
/myvol/full/Dockerfile:7 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:8 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:24 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:25 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:60 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:61 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:71 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:75 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:76 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:82 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:82 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:103 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:104 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:106 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:121 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:122 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:126 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:137 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:138 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:140 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:143 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:143 DL3013 warning: Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>` or `pip install --requirement <requirements file>`
/myvol/full/Dockerfile:143 SC2016 info: Expressions don't expand in single quotes, use double quotes for that.
/myvol/full/Dockerfile:143 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:162 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:163 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:165 SC2016 info: Expressions don't expand in single quotes, use double quotes for that.
/myvol/full/Dockerfile:165 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:183 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:184 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:186 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:186 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:201 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:207 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:208 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:219 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:220 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:229 SC2046 warning: Quote this to prevent word splitting.
/myvol/full/Dockerfile:236 DL3027 warning: Do not use apt as it is meant to be a end-user tool, use apt-get or apt-cache instead
/myvol/full/Dockerfile:241 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:242 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:247 DL3008 warning: Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
/myvol/full/Dockerfile:247 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:247 DL3009 info: Delete the apt-get lists after installing something
/myvol/full/Dockerfile:247 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:247 DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
/myvol/full/Dockerfile:253 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:254 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:260 SC2086 info: Double quote to prevent globbing and word splitting.
/myvol/full/Dockerfile:271 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
/myvol/full/Dockerfile:277 SC1091 info: Not following: File not included in mock.
/myvol/full/Dockerfile:282 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:283 DL3048 style: Invalid label key.
/myvol/full/Dockerfile:288 SC2094 info: Make sure not to read and write the same file in the same pipeline.
/myvol/full/Dockerfile:295 SC2045 error: Iterating over ls output is fragile. Use globs.
/myvol/full/Dockerfile:300 DL3004 error: Do not use sudo as it leads to unpredictable behavior. Use a tool like gosu to enforce root
/myvol/full/Dockerfile:300 SC2027 warning: The surrounding quotes actually unquote this. Remove or escape them.
/myvol/full/Dockerfile:300 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
```
</details>

Created a new issue which is not part of this epic https://github.com/gitpod-io/workspace-images/issues/736
