### ISSUE TITLE
Promoting workspace images from Google Artifact Registry to Dockerhub

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/workspace-images#636]
## Is your feature request related to a problem? Please describe

With dazzle v2 rewrite we have replaced cicrleci with GH actions, and push images to an internal Google Artifact Registry, prior to making them available on Docker Hub. The GAR is an internal registry and public does not have access to it. Therefore, the images should be published in Dockerhub too.

## Describe the behaviour you'd like

There should be a <del>GH action workflow which kicks in periodically </del> `step that` should sync all the missing image tags for all the `workspace-xxx` images from GAR to Dockerhub including the `latest` tag.

It will use `skopeo sync` with source as a `promote-images.yml` which will contain all the image names that we want to sync from GAR to DH.
If we add more combinations to our `dazzle.yaml` file then we will make corresponding changes in `promote-images.yml` so that wflow is able to push the new images to DH.

## Describe alternatives you've considered

* Pulling the image from GAR and then using docker push to push it to Dockerhub - This was just a lot of overhead
* Directly pushing to dockerhub instead of GAR - This can cause disruption to users if there is an issue with the images. We want a more controlled way of doing this.

**Comment by princerachit** [comment]
Unfortunately manual workflows can only be triggered on the default branch
![image](https://user-images.githubusercontent.com/32481722/150498237-30dd9af3-2535-4612-af76-f99cc85b9b92.png)


So the [commit](https://github.com/gitpod-io/workspace-images/pull/593/commits/a59b6280ac111f6e6e3690ea905e7b39d7e90813) to convert promote workflow to manual cannot be tested until the PR is merged.

**Comment by princerachit** [comment]
I suggest that we should merge our PR ASAP and fix anything that is broken post that. The only broken wrokflows would be the one that depend on default branch. Fixing would be easy. WDYT @kylos101

**Comment by kylos101** [comment]
Hey @princerachit , the name for #636  says to push workspace-full, but its PR #637 says to push all images, and the code indicates we're pushing the balance of the combinations we have to date. Can you update the title of #636 accordingly?

Let's focus on `workspace-full` for now, I added some tasks to #574, which is related to PR #593, can you take a peek? We should be in a position to merge that soon, and then circle back to #636 and #637.

**Comment by princerachit** [comment]
> Hey @princerachit , the name for #636 says to push workspace-full, but its PR #637 says to push all images

The PR links to the `Future` section of the issue. We can break this into two issues and point to the new issue in the PR.


> and the code indicates we're pushing the balance of the combinations we have to date

We are only pushing workspace-full image.  See [this line](https://github.com/gitpod-io/workspace-images/blob/b1da33937962e144c1860b1c3b2c4eccefbf14a2/.github/workflows/image-promote.yml#L71)

> Let's focus on workspace-full for now, I added some tasks to #574, which is related to PR #593, can you take a peek? We should be in a position to merge that soon, and then circle back to #636 and #637. edit: I started the review today, and plan to finish tomorrow.

👍🏾

**Comment by princerachit** [comment]
I have updated this issues description. Now it talks about pushing all the images to DH using a cron GH Action. I updated this as it was creating confusion. The intermediate push to DH only for workspace-full is not part of this issue.

**Comment by princerachit** [comment]
I have updated the description further after having a discussion with @kylos101
