### ISSUE TITLE
Thoughts on asdf-vm

### ISSUE THREAD

**Issue by rmacklin** [gitpod-io/workspace-images#64]
I noticed that the `workspace-full` image is installing multiple version managers for different languages ([nvm](https://github.com/gitpod-io/workspace-images/blob/aa3721916d9108af03da7da778c1e9fe12e2c672/full/Dockerfile#L120), [pyenv](https://github.com/gitpod-io/workspace-images/blob/aa3721916d9108af03da7da778c1e9fe12e2c672/full/Dockerfile#L128), [rvm](https://github.com/gitpod-io/workspace-images/blob/aa3721916d9108af03da7da778c1e9fe12e2c672/full/Dockerfile#L139)), or in some cases hardcoding a version ([go](https://github.com/gitpod-io/workspace-images/blob/aa3721916d9108af03da7da778c1e9fe12e2c672/full/Dockerfile#L78)).

I'm curious what your thoughts would be on managing all of this through [asdf-vm](https://github.com/asdf-vm/asdf):
> asdf-vm is a CLI tool that can manage multiple language runtime versions on a per-project basis. It is like gvm, nvm, rbenv & pyenv (and more) all in one!

In addition to consolidating the separate version managers into one tool, this would allow other versions of `go` to be installed if you want to check something in another version, and also enable you to install plugins for any of the [other languages that are supported](https://asdf-vm.com/#/plugins-all?id=plugin-list).

Anyway, I just wanted to gather your thoughts. Keep up the great work!

**Comment by svenefftinge** [comment]
Haven't heard of that tool. Sounds pretty good to me. @jankeromnes what's your take on that?

**Comment by jankeromnes** [comment]
Cool, thanks a lot for the tip! Is this something that many developers know and will expect to have in their workspaces? It would also be interesting to see how it compares to our current version managers on a per-language basis (i.e. does it work as well or better?); and to other more generic version managers like Sdkman, LinuxBrew or Nix.

The most important thing to me is that, for each language we have something that just works flawlessly, and it's a plus if developers might already know the tool we use & discover it by themselves (as opposed to having to learn our own custom ways of doing things).

If `asdf-vm` does a fantastic job with Go versions, I'd love to have it and advocate it to our Go developers.

**Comment by prabhu** [comment]
asdf doesn't work quite well with nodejs especially `npm install -g`. For java, sdkman seems to be the best.
