### ISSUE TITLE
Restrict push to GAR from main branch only

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/workspace-images#652]
This is to restrict the workload federation and permissions. At the moment any branch can be used to authenticate against the oidc provider configured for Github in the google project for the workspace-images repo. Although the permission to trigger the actions only resides with maintainers, this is still prone to human errors.

Add a condition in the oidc provider to only allow authentication when the branch being used is the default branch,

**Comment by princerachit** [comment]
Fixed this my manually editing the conditions in the provider. Added the following condition:

`'refs/heads/master' == attribute.ref`

**Comment by princerachit** [comment]
Also raised a PR to add this example in the upstream. https://github.com/google-github-actions/auth/pull/121

**Comment by kylos101** [comment]
> Fixed this my manually editing the conditions in the provider. Added the following condition:
> 
> `'refs/heads/master' == attribute.ref`

Hi @princerachit can you share a link to the code where you made this configuration change? For example, if we had to set GAR up again, where is this captured?

**Comment by princerachit** [comment]
I updated the resource manually from Google console otherwise I would have needed to create a new provider. This is how the  creation of the provider would look like. I tested using this script first and then made the manual change. I have created [this issue](https://github.com/gitpod-io/workspace-images/issues/654) to move these resource creation to terraform

```bash
set -Eeuo pipefail
export PROJECT_ID=gitpod-artifacts
export OIDC_NAME=workspace-images-gha-test
export WLOAD_IDENTITY_POOL=workspace-images-github-actions

gcloud iam workload-identity-pools providers create-oidc "${OIDC_NAME}" \
  --project="${PROJECT_ID}" \
  --location="global" \
  --workload-identity-pool="${WLOAD_IDENTITY_POOL}" \
  --display-name="Workspace provider test" \
  --attribute-mapping="google.subject=assertion.sub,attribute.actor=assertion.actor,attribute.repository=assertion.repository,attribute.ref=assertion.ref" \
  --attribute-condition="'refs/heads/updated-workload-identity-test' == attribute.ref" \
  --issuer-uri="https://token.actions.githubusercontent.com"  

gcloud iam workload-identity-pools providers describe "${OIDC_NAME}" \
  --project="${PROJECT_ID}" \
  --location="global" \
  --workload-identity-pool="${WLOAD_IDENTITY_POOL}" \
  --format='value(name)'

```
