### ISSUE TITLE
State of version managers

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/workspace-images#66]
Here are the **currently installed** version managers in `workspace-full`, and what they can do:

| Version Manager | Language / Technology | User-configurable | Persistent Packages | Persistent Version | Also controls IDE & LS |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [`nvm`](https://github.com/creationix/nvm) | Node.js | ✅ | ✅ | ✅<sup>-1</sup> | ❌ |
| [`pyenv`](https://github.com/pyenv/pyenv) | Python | ✅ | ✅<sup>0</sup>  | ✅<sup>1</sup> | ❌ |
| [`sdk`](https://sdkman.io) | Java + [...](https://sdkman.io/sdks) | ✅ | ✅<sup>2</sup> | ❌ | ❌ |
| [`rvm`](https://rvm.io/) | Ruby | ✅ | ✅<sup>3</sup> | ✅<sup>4</sup> | ? |
| [`rustup`](https://rustup.rs/) | Rust | ? | ? | ? | ? | ? |
| [`composer`](https://getcomposer.org/) | PHP | ? | ? | ? | ? | ? |
| ❌ | Go | | | | | |
| ❌ | C/C++ | | | | | |

<sup>-1</sup> node binaries are not persisted in /workspace, but versions can be specified with a [`.nvmrc` file](https://github.com/creationix/nvm#nvmrc)
<sup>0</sup> `pip install <lib>` is persisted in `/workspace/.pip-modules` which is also configure to be `PYTHONUSERBASE`, in addition `PIP_USER=yes` enforces the `--user` flag for `pip`
<sup>1</sup>`pyenv local <version>` will create a `.python-version` in your workspace (but new binaries are installed in `~/.pyenv/shims/`, so not persisted)
<sup>2</sup> Maven and Gradle packages are now persisted in /workspace, see #60 #61
<sup>3</sup>`gem install <gem>` & `bundle install` are now persisted in /workspace, see #67
<sup>4</sup> `rvm install ruby-2.4.1` is not persisted in /workspace, see https://github.com/gitpod-io/gitpod/issues/353, but version can be specified with a [`.ruby-version` file](https://rvm.io/workflow/projects#project-file-ruby-version)

---

Here are potential new version managers we **could install**, and what they can do:

| Version Manager | Language / Technology | User-configurable | Persistent Packages | Persistent Version | Also controls IDE & LS |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [`asdf`](https://asdf-vm.com) | [...](https://asdf-vm.com/#/plugins-all?id=plugin-list) | ? | ✅<sup>1</sup> | ✅<sup>2</sup> | ? |
| [`gvm`](https://github.com/moovweb/gvm) | Go | ? | ? | ? | ? |
| [`rbenv`](https://github.com/rbenv/rbenv) | Ruby | ? | ? | ? | ? |

<sup>1</sup>`asdf local <name> <version>` will create a `.tools-version` in your workspace
<sup>2</sup> new `asdf` binaries are installed in `$ASDF_DATA_DIR`, which can be configured e.g. to `/workspace/.asdf`

---

- If you see any errors, please point them out, I'll fix the tables above.
- If you'd like to suggest more tools for consideration, please reply to this issue, I'll add them.

**Comment by jankeromnes** [comment]
Maybe it makes sense to install `asdf-vm` to manage Go versions? But I don't know what this means for our current Go support, how it will play with the Go VS Code extension, or if Go developers will find that convenient.

@sr229 I notice that `asdf-vm` can also manage versions of Dart and .NET Core. Would that seem useful to you, or do you prefer using the single version of Dart and .NET currently installed in our Dockerfiles?

**Comment by sr229** [comment]
I think that would be useful in a development context, but we shpuld have a system version just in case they want to use the packaged version

**Comment by AlexTugarev** [comment]
@jankeromnes I updated the modules persistence for Python.

**Comment by AlexTugarev** [comment]
`Also controls IDE & LS` might be obsolete.

As we now switch to VS Code extensions the best case is, that the extension manages everything and lets you decide what to use in a project/repo. Every installed interpreter/sdk/etc. should be available in the IDE and the environment shouldn't tell what what to be used there, but you.

**Comment by svenefftinge** [comment]
What is the purpose of this "issue"? Is there an action we can take to close it eventually?

**Comment by superloach** [comment]
In terms of Go, I've had pretty good success using the `golang.org/dl/goX.YZ` packages as so:
```sh
go version
# go version go1.15 linux/amd64

go get golang.org/dl/go1.16
go1.16 download

rm -r ~/go
mv ~/sdk/go1.16 ~/go

go version
# go version go1.16 linux/amd64 
```

**Comment by atduarte** [comment]
Given this seems largely outdated and there's no apparent action to be made, I will close this.
