### ISSUE TITLE
gitpod/workspace-mysql can no longer pip install mysqlclient

### ISSUE THREAD

**Issue by tylerstephens814** [gitpod-io/workspace-images#679]
### Bug description

When creating a new workspace under the `gitpod/workspace-mysql` image, running `pip install mysqlclient` results in an error
```
Running setup.py install for mysqlclient ... error
...
MySQLdb/_mysql.c:46:10: fatal error: Python.h: No such file or directory
   46 | #include "Python.h"
      |          ^~~~~~~~~~
```
This was working 100% a week or so ago.
I noticed that the docker image was updated 7 hours ago. https://hub.docker.com/r/gitpod/workspace-mysql

Also I noticed something strange:
- `python --version` => `3.8.12`
- `python3 --version` => `3.8.10`
I looked back at a different project and these two versions are both `3.8.12`

### Steps to reproduce

- Start a new workspace
- Change default image to use `FROM gitpod/workspace-mysql`
- `pip install mysqlclient`

### Expected behavior

Should install the package and run the setup.py as part of pip

**Comment by atduarte** [comment]
Hi, @tylerstephens814. Just tested it and it also fails for me. We will look into that.

In the meantime, as a workaround you can do `sudo apt-get install python3-dev`. It should fix the issue.

**Comment by tylerstephens814** [comment]
Ok, tried the work around, and it seemed to work for installing mysqlclient, but it surfaced some other problems:
When I run the Django project, it complains that it can't find certain modules (`chardet` specifically). Doing a pip freeze reveals that `chardet` is indeed installed.

Digging a little deeper:
The default python: `which python` `/home/gitpod/.pyenv/shims/python`
The default pip: `which pip` `/usr/bin/pip`
^^ Is it right that one point to the env while the other doesn't?

Looks like there a few versions of pip installed `pip   pip3  pip3.8  pipenv`
`which pip3`      `/usr/bin/pip3`
`which pip3.8`   `/home/gitpod/.pyenv/shims/pip3.8`
`which pipenv`  `/home/gitpod/.pyenv/shims/pipenv`

By installing via `pip3.8 install -r requirements.txt` it seems to install the packages in the correct location.

**Comment by utam0k** [comment]
@tylerstephens814 Hi, Does this solve the `mysqlclient` problem? The problem with pyenv and the system's python seems to be a different problem, right? If ok, please close this issue 🙏 
I'd like to concentrate on `$PATH` problem in #694 .

**Comment by utam0k** [comment]
@tylerstephens814 Thanks for your contribution 😍
