### ISSUE TITLE
pip install in editable mode no longer works

### ISSUE THREAD

**Issue by AntonyMilneQB** [gitpod-io/workspace-images#694]
### Bug description

Since the recent changes to `gitpod/workspace-full`, doing `pip install -e` no longer works in my repo. The same problem exists for `gitpod/workspace-python`. The `legacy-dazzle-v1` works fine. `pip install` without `-e` works fine.

Possibly related:
https://github.com/gitpod-io/workspace-images/issues/679 (I saw the same error at some stage while fiddling around trying to get it working)
https://github.com/gitpod-io/workspace-images/issues/664
https://github.com/gitpod-io/workspace-images/issues/655

### Steps to reproduce

Here's my repo: https://github.com/kedro-org/kedro. You'll find it all works fine if you `pip install -e .` (which is run in .gitpod.yml already), but only because I've specified `image: gitpod/workspace-full:legacy-dazzle-v1`. If we try instead with `workspace-full` or `workspace-python` I will instead get the following error. All dependencies install fine, but then it's the package itself that fails.

I'm guessing this is due to the combination of `--user` and `-e`, as in https://github.com/pypa/pip/issues/7953, but unfortunately none of the workarounds there are working. As above, this used to work fine before the change to dazzle v2.

```    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/workspace/kedro/setup.py'"'"'; __file__='"'"'/workspace/kedro/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /workspace/kedro/
    Complete output (18 lines):
    running develop
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/test-easy-install-286.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/lib/python3.8/site-packages/
    
    This directory does not currently exist.  Please create it and try again, or
    choose a different installation directory (using the -d or --install-dir
    option).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/workspace/kedro/setup.py'"'"'; __file__='"'"'/workspace/kedro/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

### Expected behavior

Python package should install successfully.

### Example repository

I tried making a minimal example [here](https://github.com/AntonyMilneQB/minimal) but this doesn't demonstrate the bug - `pip install -e .` works fine there. I'm not sure why this one works but my complete kedro example doesn't.

**Comment by AntonyMilneQB** [comment]
P.S. I was wondering whether this was related to the [change to `PIP_USER`](https://github.com/gitpod-io/workspace-images/pull/461/files), but given how long ago that change happened, and the fact that the variable is set the same in `legacy-dazzle-v1` which _does_ work I don't think it can be.

**Comment by utam0k** [comment]
@AntonyMilneQB Hi, first of all, thanks for your report!
I did a little search. Perhaps this is a problem with `$PATH`.

```console
gitpod ~ $ echo $PATH | sed 's/:/\n/g'
...
/usr/local/sbin
/sbin
/workspace/.cargo/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/local/bin
/bin
/usr/sbin
/home/gitpod/.pyenv/shims
...
/usr/bin
/home/gitpod/.pyenv/bin
...
```

As a test, I changed the `$PATH` so that pyenv takes precedence. Then it worked fine.
https://github.com/utam0k/kedro/tree/gitpod-workspace-full

This is a probably a bug with dazzle

**Comment by utam0k** [comment]
I've created the issue.
https://github.com/gitpod-io/dazzle/issues/42

**Comment by AntonyMilneQB** [comment]
Thanks very much for the quick response @utam0k. I think a fix to dazzle may also fix some of the related issues I linked to.

**Comment by utam0k** [comment]
I'm going to consolidate the `$PATH` problem into #664, so let me close this one. @AntonyMilneQB Thanks for raising this issue, please keep watching #664 🙏

**Comment by utam0k** [comment]
@AntonyMilneQB I've released new images, and it worked fine.
https://github.com/utam0k/kedro/commit/12511e8d8a4de97a7d95901369ef8d34a55821ba

**Comment by AntonyMilneQB** [comment]
Awesome, thanks very much @utam0k!
