### ISSUE TITLE
Ability to use a custom  user instead of gitpod 

### ISSUE THREAD

**Issue by mwaaas** [gitpod-io/workspace-images#695]
I would like to use workspace-image with a custom user as of now the image comes with gitpod user.

**Comment by axonasif** [comment]
Continuing with https://github.com/gitpod-io/workspace-images/pull/686#issuecomment-1042876109, you can use a custom dockerfile and use that from your `.gitpod.yml` where you rename the `gitpod` user, fix `/home` useraccount paths, re-assign uid and gid and stuff.[^1]

[^1]:https://wiki.archlinux.org/title/users_and_groups

**Comment by kylos101** [comment]
Agreed, thank you @axonasif !

@mwaaas let us know if you're still having trouble, and if so, what you're unable to do? For now I am going to close this issue.

**Comment by mwaaas** [comment]
Hey @axonasif, @kylos101 
So the change that I had was adding USER as argument but if you don't pass it during build it was picking gitpod as the default user.

That won't break the other places where USER has not been added.
