### ISSUE TITLE
Create new dazzle release & use for main and PR workflows

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#721]
There are new commits in dazzle main, [please create a new release tag to build the next dazzle version](https://github.com/gitpod-io/dazzle/blob/main/.github/workflows/release.yaml#L6), update the workflows in `workspace-images` to use the newly built version of dazzle, and test to assert it is working as advertised.

Why? [The latest dazzle will solve path issues](https://github.com/gitpod-io/dazzle/issues/42), which will help solve many issues for users. [[1](https://github.com/gitpod-io/workspace-images/issues/694)][[2](https://github.com/gitpod-io/workspace-images/issues/664)]

**Comment by utam0k** [comment]
- https://github.com/gitpod-io/workspace-images/blob/447314894a511e0892376acc610b828e2390c4b6/.github/workflows/push-main.yml#L46
- https://github.com/gitpod-io/workspace-images/blob/447314894a511e0892376acc610b828e2390c4b6/.github/workflows/pull-request.yml#L27

**Comment by utam0k** [comment]
I released.
https://github.com/gitpod-io/dazzle/releases/tag/v0.1.7
