### ISSUE TITLE
Separate workflow which pushes to Docker Hub

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#728]
## Is your feature request related to a problem? Please describe

We currently push to Docker Hub each time we merge to the default branch.

## Describe the behaviour you'd like

- We do not want to push to Docker Hub with each merge to the default branch.
- We want to trigger a push of content to Docker Hub separately, perhaps weekly.
- In this way, there will be less versions of `workspace-full` floating around out there, and less images that much be cached on nodes.

## Additional context

#713

**Comment by kylos101** [comment]
Hey @princerachit may I ask you to work this issue, prior to the other items in #713, this way it gets merged to main beforehand? That will give us the ability to merge to main without always pushing to Docker Hub.

CC: @utam0k for awareness

**Comment by princerachit** [comment]
>In this way, there will be less versions of workspace-full floating around out there, and less images that much be cached on nodes.

At this moment we sync all image tags from GAR to DH. Even if we push weekly we would be shipping multiple versions of workspace-full. I guess you mean that there should be less changes in the `latest` tag of workspace full.
