### ISSUE TITLE
Any plans to support arm64?

### ISSUE THREAD

**Issue by Cyber1000** [gitpod-io/workspace-images#744]
Do you plan to support arm64-docker-images?

https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile (I assume this is workspace-base?) is based on buildpack-deps:focal and can be build out of the box on arm64.

gitpod/workspace-full would need some adjustments (at least some month ago, when I tested this)

**Comment by Cyber1000** [comment]
ok seems that dazzle.yaml puts together various combinations to create your images, if I see it right. Base is little bit more than https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile (3 additional chunks)

As said would be nice to have arm64 too, no idea how much work this would involve, dazzle is new to me.

**Comment by princerachit** [comment]
Hi, we [do not have plans](https://github.com/gitpod-io/gitpod/pull/7937#issuecomment-1042718737) to support arm64 in near future at least.
