### ISSUE TITLE
Pre-install popular/amazing CLI tools

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/workspace-images#76]
E.g.

- [x] `jq`
- [ ] `rg`
- [ ] `fd`
- [ ] `z`
- [ ] `fzf`
- [ ] `mtr`
- [ ] `hub` (#77)

Inspiration: [this thread](https://twitter.com/krisnova/status/1109618657305333761) and [this post](https://remysharp.com/2018/08/23/cli-improved)

Also maybe add tips about them in the Gitpod loading screen, see https://github.com/gitpod-io/gitpod/issues/93

**Comment by meysholdt** [comment]
maybe have a page in the documentation where we list their name, purpose, and link to the official doc.

**Comment by meysholdt** [comment]
see also #18

**Comment by meysholdt** [comment]
Lots of tweets where people unveil what they use most:

https://twitter.com/wycats/status/1127253486268293121

**Comment by deepflame** [comment]
If I may add some more ideas here:

- [silversearcher-ag](https://github.com/ggreer/the_silver_searcher)
- [lazygit](https://github.com/jesseduffield/lazygit)
- neovim
- tmux
- zsh

**Comment by JesterOrNot** [comment]
PR created :smiley:

**Comment by aledbf** [comment]
Closing. This is an ancient issue. Would you mind opening a new issue with the missing tools?
