### ISSUE TITLE
Builds are failing in GH Actions

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/workspace-images#767]
### Bug description

The combine step for workspace images is getting stuck in random test steps for hours before the action times out.
e.g. Main branch:
https://github.com/gitpod-io/workspace-images/actions/runs/1976439848/attempts/1

Pull Requests:
https://github.com/gitpod-io/workspace-images/actions/runs/1970304905/attempts/1

### Steps to reproduce

Raise a PR or try to retrigger build from main action

### Expected behavior

Build should succeed

**Comment by kylos101** [comment]
@princerachit great catch! Thank you for scheduling the issue, too. :muscle: 

The last successful build from main was [7 days ago](https://github.com/gitpod-io/workspace-images/actions/runs/1944062831), prior to which they were taking < 1h.

**Comment by princerachit** [comment]
Build worked locally for all these commits:

9bde118085bd7f7816e474c266bab9fffea8ea2f

ccee8da04a1971ddc7dc596697dde36d185eef6f

e93dff6546dc652e6546f3b534a23ed60acb3d91

9480e14830655c986496ecdcf2626613431b6dc3 (main branch)


Something changed in wrt either Github actions runner OR in our images (maybe the size?)

**Comment by kylos101** [comment]
I'm not sure what you mean by locally.

main history:
![image](https://user-images.githubusercontent.com/1272076/158247031-253ba63a-bf4e-4454-8f59-b577e7ac0f95.png)

You may be onto something regarding the Github Actions runner. To test if it's the runner, you could check to see how long it takes to run in a Gitpod workspace, just be sure to set the timeout to 3h (so you don't get clipped at the 1h mark).

**Comment by princerachit** [comment]
@kylos101 from local I meant in [gitpod workspace](https://github.com/gitpod-io/workspace-images/blob/main/CONTRIBUTING.md#locally).

It takes less than 2 hours
