### ISSUE TITLE
[feat] add lang-elixir as an available chunk

### ISSUE THREAD

**Issue by emattiza** [gitpod-io/workspace-images#775]
This is a tracking issue around adding a lang-elixir chunk and image to the available gitpod workspaces in support of folks using gitpod who may want to write an Elixir application. This will be followed by a draft pr, and I can promote to ready-for-review should the team find the proposed addition acceptable.

In addition, I can make any contributions for language support to the website docs under a new elixir section.

**Comment by utam0k** [comment]
I agree to add support for elixir. @gitpod-io/engineering-workspace WDYT

**Comment by kylos101** [comment]
Hi @utam0k as a separate image yes, but, not as an additional chunk in`workspace-full` (it is too big).

**Comment by utam0k** [comment]
@kylos101 That's right. I agree with you. I forgot to take `workspace-full` into consideration.

**Comment by Furisto** [comment]
This has been completed. Thanks @emattiza.
