### ISSUE TITLE
Add `lldb` to `lang-c` chunk

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/workspace-images#799]
I'd like to suggest adding the [LLDB debugger](https://lldb.llvm.org/) (`lldb`) to [lang-c chunk](https://github.com/gitpod-io/workspace-images/blob/main/chunks/lang-c/Dockerfile) (and thus to `-full`, right?).  As an alternative to `gdb` for those who are so inclined, and who are using `clang`/`clang++`.

**Comment by atduarte** [comment]
Thanks for the suggestion @david-bakin. We currently don't have the bandwidth to look into adding this. Although you can create your own Docker image very easily. See https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile for more details.

**Comment by david-bakin** [comment]
I have added it for myself via a custom Docker image (great feature!) - doesn't work 100% yet but I'm working to resolve that.  

I assume you accept PRs (from random people outside of Gitpod) for _changes_ to existing chunks?  The contribution guidelines for this repo are (understandably) focused on _new_ images or chunks.

**Comment by atduarte** [comment]
The issues are probably be related with https://github.com/gitpod-io/gitpod/issues/5705 that we will be looking at soon. 🤞 

>  assume you accept PRs (from random people outside of Gitpod) for changes to existing chunks?
Yes! Given the CLA is signed and we agree that the given tool should be included. We need to evaluate each case to ensure the image doesn't get bloated.

@kylos101 Assuming you are more familiar with the C ecosystem than I am, do you think `lldb` should be added?

**Comment by kylos101** [comment]
Hey @atduarte no, I am not familiar with C. 

@david-bakin I recommend [reaching out to our community](https://www.gitpod.io/community), to see if they can help you with the custom Docker image you are working. 

For now, I am going to close this issue. We try to encourage users to make customizations for "preferred things" (like a debugger of choice).
