### ISSUE TITLE
Sync images times out often on merge to main

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#805]
This step in the build action often times out.

https://github.com/gitpod-io/workspace-images/blob/3f0988f2d06768d22d0aa1454ef0e963b0db65f3/.github/workflows/push-main.yml#L146-L151

When merging back to main, until we fix this, it is important to "come back here", and check the related Action in Github (like 1.5h later), to assert it finished. If not, it may need to be rerun 1-2 times! [Example.](https://github.com/gitpod-io/workspace-images/runs/6015215025?check_suite_focus=true)

**Comment by Neelaksh-Singh** [comment]
Would adding a simple timeout-minutes for the job do the trick? If so how many minutes should we ideally be giving for the same?

**Comment by jenting** [comment]
I did not see this error recently 🚀

**Comment by sagor999** [comment]
Going to close this issue as it no longer happens.
Inspected this job and have not seen any failures like this in the last 3 months:
https://github.com/gitpod-io/workspace-images/actions/workflows/push-main.yml
