### ISSUE TITLE
Haskell support

### ISSUE THREAD

**Issue by andreabedini** [gitpod-io/workspace-images#822]
Hi there,

as per the [CONTRIBUTING.md](https://github.com/gitpod-io/workspace-images/blob/main/CONTRIBUTING.md#before-you-start) guide, I would like to contribute support for the Haskell language.

In the Haskell ecosystem things have been changing quite a lot and I suggest the following as the better approach (in terms of inclusiviness).

- Install the [ghcup](https://haskell.org/ghcup) toolchain installer. This works similarly to rustup in the Rust ecosystem and can install (and switch between) any version of ghc, cabal, stack and the haskell-language-server.
- Use ghcup to install a default version of all four (ghc, cabal, stack and the haskell-language-server)
- Make sure that cabal, stack and haskell-language-server caches are persistent (e.g. `/workspace/.cabal`, `/workspace/.stack`, ...)
- Make sure that the directory where ghcup installs binaries is in PATH

There is one thing I don't know how to approach: Where should ghcup install things? I see that rustup installs the toolchain under HOME. But AFAIK any change outside the workspace won't be persisted. So if I user wants a different version of GHC (which is quite common in the haskell ecosystem) that won't be persistent. We could preinstall many versions of GHC but they are quite heavy in terms of disk space. What's the right approach here?

There are a couple of nuisances, this time completely dependent on the Haskell ecosystem.

1) GHCup can install ghc and stack but stack will insist on reinstalling its own version of ghc (not using GHCup). I am inclined to just let this happen (it will be persisted in `/workspace/.stack` anyway).

2) There could be a problem if the user makes stack to self-upgrade, but this might be rare. This could be easily solved by not installing stack with GHCup but it's tempting to use a single tool to install everything.

I have already done most of this entirely in `.gitpod.yml` (see [here](https://github.com/andreabedini/template-haskell/blob/main/.gitpod.yml)). The haskell-language-server project also seems to use gitpod ([here](https://github.com/haskell/haskell-language-server/blob/master/.gitpod.yml)).

Let me know if there's interest. No hard feeling if you believe we should stick to a pure "user-space" solution (i.e. `.gitpod.yml`)

:heart:

**Comment by ghuntley** [comment]
Howdy @andreabedini!

ICMYI we have two templates that provide inspiration on how to do λ on Gitpod 😉

- https://github.com/gitpod-io/template-haskell (stack)
- https://github.com/gitpod-io/template-haskell-nix (nix)

Personally don't have much experience with ghcup but enough with stack, nix and the PvP to know that adding heading down the ghcup path in workspace-full isn't the path that wish to head down as (unfortunately) the Haskell community is so fragmented. 

> What's the right approach here?

A chunk could be created at https://github.com/gitpod-io/workspace-images/tree/main/chunks but it would unlikely be included in the default image as we want to keep the workspace-full size as small as possible to make workspace boot times fast.

**Comment by andreabedini** [comment]
Howdy! Thanks for you thorough answer. I think there have been some improvements in the last past few years but I see what you are saying. GHC installs are a bit heavy so I understand it they won't go into the default image.

I will stick with installing everything myself either with a image or from gitpod.yml. Feel free to ping me if your or gitpod wants to revisit Haskell support!

**Comment by atduarte** [comment]
Aloha! Truly appreciate you coming forwarding and offering your help. 🧡 

Currently, we are at capacity and struggling to keep up with the existing images so we are trying to keep it as lean as possible. Will be looking into this for sure in the future, but wanted to let you know that right now we won't be able to.

Hope your experience with Gitpod is still great! 🙌
