### ISSUE TITLE
When to update latest tags?

### ISSUE THREAD

**Issue by tnir** [gitpod-io/workspace-images#828]
Latest tags of all tags by https://hub.docker.com/u/gitpod looks like having no updates for 12 days while docs about release cycle says as follows:
> [Update latest tags](https://github.com/gitpod-io/workspace-images/blob/e4307d234c06a6baf7e0ae50854a29913ce8ea1c/.github/workflows/dockerhub-release.yml) - Weekly update the latest tag of all images in dockerhub with current latest datetimestamp image

How to update latest tags of the images?

----

@sagor999 Sorry. Just found workflows around release cycle. https://github.com/gitpod-io/workspace-images/blob/e4307d234c06a6baf7e0ae50854a29913ce8ea1c/CONTRIBUTING.md#release

Unlike written, it looks like manual 😆 : https://github.com/gitpod-io/workspace-images/blob/e4307d234c06a6baf7e0ae50854a29913ce8ea1c/.github/workflows/dockerhub-release.yml#L1-L4

_Originally posted by @tnir in https://github.com/gitpod-io/workspace-images/issues/813#issuecomment-1109225769_

**Comment by tnir** [comment]
#829 is also waiting for this.

**Comment by jenting** [comment]
👋  Please refer to this issue #836
