### ISSUE TITLE
[actions] tag latest as weekly

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#836]
### Describe what you would like
The workspace-images are tagged as latest on a regular cadence.

### How
The related [GitHub Action](https://github.com/gitpod-io/workspace-images/actions/workflows/dockerhub-release.yml) in this repo is updated to run every Tuesday at 10:00 CEST.

### Notes
The first pull of the image will be slow (as it has to pull and be cached in each cluster's IPFS).

**Comment by jenting** [comment]
> The related [GitHub Action](https://github.com/gitpod-io/workspace-images/actions/workflows/dockerhub-release.yml) in this repo is updated to run every Tuesday at 10:00 CEST.

Awesome.

**Comment by kylos101** [comment]
@jenting someone from Team Workspace will still have to "release" the workflow, but, at least this way it'll get triggered.

The job currently sends an email to the team, but, we should consider moving that notification to Slack.

**Comment by jenting** [comment]
🤔  I thought it it trigger by cron by GitHub action.

**Comment by kylos101** [comment]
> thinking I thought it it trigger by cron by GitHub action.

Trigger by cron will initiate action, but, the workflow is protected. Someone from the team must still approve the deployment.

**Comment by tnir** [comment]
https://github.com/gitpod-io/workspace-images/actions/workflows/dockerhub-release.yml?query=event%3Aschedule always fails.

Config introduced in #837 does not work.

**Comment by jenting** [comment]
> https://github.com/gitpod-io/workspace-images/actions/workflows/dockerhub-release.yml?query=event%3Aschedule always fails.
> 
> Config introduced in #837 does not work.

The CRON config works as expected, but the triggered GitHub action needs to be approved.
You could check the reason why we rejected the triggered GitHub action.

**Comment by tnir** [comment]
No, I do not have any questions or trouble in the deploy process automation.
