### ISSUE TITLE
[rust] cannot install additional rust target after installing a toolchain

### ISSUE THREAD

**Issue by jcornaz** [gitpod-io/workspace-images#841]
### Bug description

When using the `gitpod/workspace-rust` image, after installing a *toolchain* (e.g. "nightly"), it is no longer possible to install *targets* (e.g. "wasm32-unknown-unknown")

### Steps to reproduce

Create the following docker file:

```docker
FROM gitpod/workspace-rust
RUN rustup toolchain install nightly
RUN rustup target install wasm32-unknown-unknown
```

And try to build it. You will observe the following output:
```
Step 1/3 : FROM gitpod/workspace-rust
 ---> 97f6b75b1492
Step 2/3 : RUN rustup toolchain install nightly
 ---> Using cache
 ---> 18507d0df182
Step 3/3 : RUN rustup target install wasm32-unknown-unknown
 ---> Running in 781069322c6e
/home/gitpod/.cargo/bin/rustup: 5: Syntax error: "(" unexpected (expecting "}")
The command '/bin/sh -c rustup target install wasm32-unknown-unknown' returned a non-zero code: 2
```

### Expected behavior

It should be possible to install compilation targets. The docker file presented above should be successfully built.

**Comment by axonasif** [comment]
Now you can use **gitpod/workspace-rust:[2022-05-19-23-37-25](https://hub.docker.com/layers/workspace-rust/gitpod/workspace-rust/2022-05-19-23-37-25/images/sha256-11408ebf6299bdef9c38af2af15d3853c9e36628add4c964f24e025dcc15c001?context=explore)** on your `.gitpod.yml image:` or custom dockerfile as #840 was merged 🎉
