### ISSUE TITLE
[tool-nix] Install direnv in the Nix image

### ISSUE THREAD

**Issue by berryp** [gitpod-io/workspace-images#847]
`direnv` is a tool commonly used with Nix to auto-configure/manage shell environments and dev dependencies.

The [gitpod-ol/template-nix](https://github.com/gitpod-io/template-nix/blob/main/.gitpod.Dockerfile#L33-L36) repo installs `direnv` but it's missing from the `tool-nix` image.

I use direnv with several project, but in order to install it I need to add a custom Dockerfile to those repos which increases build and load times for my workspaces.

**Comment by woss** [comment]
Hi, I'm using this image as a bas image and the direnv Vscode extension is not picking up the installed direnv. any clue why?
