### ISSUE TITLE
gitpod/workspace-postgresql image to include postgresql-12 package (12.11) even if it was built with dazzle v2.

### ISSUE THREAD

**Issue by tnir** [gitpod-io/workspace-images#851]
@kylos101 Weird. I expect `gitpod/workspace-postgresql` image to include the latest `postgresql-12` package (12.11) if it was built with dazzle v2.

At least, it should be 12.10, which was released in 2022-02:
```
postgresql-12 (12.10-0ubuntu0.20.04.1) focal; urgency=medium

  * New upstream version (LP: #1961127).

    + A dump/restore is not required for those running 12.X.

    + However, if you have applied REINDEX CONCURRENTLY to a TOAST table's
      index, or observe failures to access TOAST datums, there has been a
      fix for this problem. Any existing corrupted indexes can be repaired
      by reindexing again.

    + Also, if you are upgrading from a version earlier than 12.9, see
      those release notes as well please.

    + Details about these and many further changes can be found at:
      https://www.postgresql.org/docs/12/release-12-10.html

 -- Athos Ribeiro <athos.ribeiro@canonical.com>  Wed, 23 Feb 2022 08:36:18 -0300
```

## Steps to reproduce

1. Launch a workspace via https://gitpod.io/#https://github.com/gitpod-io/ruby-on-rails
2. Examine postgresql-12 package version as follows:
```
$ dpkg -l | grep post
ii  postgresql-12                      12.9-0ubuntu0.20.04.1             amd64        object-relational SQL database, version 12 server
ii  postgresql-client-12               12.9-0ubuntu0.20.04.1             amd64        front-end programs for PostgreSQL 12
ii  postgresql-client-common           214ubuntu0.1                      all          manager for multiple PostgreSQL client versions
ii  postgresql-common                  214ubuntu0.1                      all          PostgreSQL database-cluster manager
```

So users need to update on dev later manually:
```
$ sudo apt update -qq; sudo apt install postgresql-12
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Recommended packages:
  sysstat
The following packages will be upgraded:
  postgresql-12
1 upgraded, 0 newly installed, 0 to remove and 197 not upgraded.
Need to get 13.5 MB of archives.
After this operation, 12.3 kB disk space will be freed.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 postgresql-12 amd64 12.11-0ubuntu0.20.04.1 [13.5 MB]
Fetched 13.5 MB in 1s (14.8 MB/s)         
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 34970 files and directories currently installed.)
Preparing to unpack .../postgresql-12_12.11-0ubuntu0.20.04.1_amd64.deb ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
Unpacking postgresql-12 (12.11-0ubuntu0.20.04.1) over (12.9-0ubuntu0.20.04.1) ...
Setting up postgresql-12 (12.11-0ubuntu0.20.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for postgresql-common (214ubuntu0.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
```

### Resources

https://github.com/gitpod-io/workspace-images/blob/8a4fcd02e7c09389af5e5e3e7860e3d69d82474a/chunks/tool-postgresql/Dockerfile#L9-L10

https://packages.ubuntu.com/focal/postgresql-12 shows:

> Package: postgresql-12 (12.11-0ubuntu0.20.04.1 and others) [security]

_Originally posted by @tnir in https://github.com/gitpod-io/workspace-images/issues/815#issuecomment-1149361611_

**Comment by tnir** [comment]
@kylos101 Thoughts?

**Comment by tnir** [comment]
Umm... is it worth to increment from 2 to 3?

The latest `gitpod/workspace-postgres@sha256:f486b10fa3455df6131fb38eeb0fd571b92d34f0fc5b05481deeb1d17f975993` was created in `2021-12-07T07:06:20.294005386Z`, but https://github.com/gitpod-io/workspace-images/pull/593 newly introduced dazzle v2 build in `2022-01-28T07:36:51Z`...

**Comment by tnir** [comment]
https://github.com/gitpod-io/workspace-images/issues/815#issuecomment-1150638832

This should be the answer 😭

**Comment by kylos101** [comment]
Hi @tnir , there are two images: https://hub.docker.com/search?q=gitpod%2Fworkspace-postgres

The title of this issue mentions `workspace-postgresql` (with `ql`).
The comment mentions `workspace-postgres` (without `ql`).

The introduction of `gitpod/workspace-postgresql` was an accident as part of the dazzle v2 upgrade. In other words, it was not intentional (as a I recall) to create a 2nd repo.

It looks like you are referencing `gitpod/workspace-postgres` [in your comment](https://github.com/gitpod-io/workspace-images/issues/851#issuecomment-1150638409).

As a short term solution, may I ask you to try `gitpod/workspace-postgresql`? 

For the long term, I will get back to you in this issue.

**Comment by tnir** [comment]
@kylos101 Thanks.

> It looks like you are referencing gitpod/workspace-postgres https://github.com/gitpod-io/workspace-images/issues/851#issuecomment-1150638409.

I would have been confused between two images in my previous comments.

> As a short term solution, may I ask you to try gitpod/workspace-postgresql?

Updating `FROM` section from `.gitpod.Dockerfile` with `gitpod/workspace-postgresql` looks like not so easy to me.

I would add the numbers of pulls of these images as of writing:

- https://hub.docker.com/r/gitpod/workspace-postgresql: Pulls 3.3K
- https://hub.docker.com/r/gitpod/workspace-postgres: Pulls 100K+

**Comment by kylos101** [comment]
Hey @tnir the main build is running now, and it'll be available as a tagged image on DockerHub (barring failures with he related Github Action) in roughly 1-2 hours. :pray:

**Comment by kylos101** [comment]
Closing, the main build was successful, thanks again for your help, @tnir ! :pray:

**Comment by tnir** [comment]
Thank you so much @kylos101. `[gitpod/workspace-postgres:latest](https://hub.docker.com/r/gitpod/workspace-postgres)` user would get the first release for six months next week!
