### ISSUE TITLE
[Suggestion] - Workspace Quarkus

### ISSUE THREAD

**Issue by jeanphibaconnais** [gitpod-io/workspace-images#863]
Hi 👋 
is it pertinent to have a Quarkus workspace ? if yes, I can contribute, I worked on a template for this framework.

**Comment by atduarte** [comment]
Hey, Jean! Thank you for offering your help 🙌 Currently, we are at capacity and struggling to keep up with the existing images so we are trying to keep it as lean as possible. We are looking for ways to make this more scalable, but in the meantime we are focusing only on the most requested languages/frameworks/ecosystems. Potentially in the future 🙏

**Comment by jeanphibaconnais** [comment]
Hi @atduarte , ok thank's for your message !
