### ISSUE TITLE
[python] Consider supporting `poetry` 

### ISSUE THREAD

**Issue by andrewcstewart** [gitpod-io/workspace-images#870]
## Is your feature request related to a problem? Please describe

[`poetry`](https://python-poetry.org/) is an increasingly common dependency/version manager for Python developers.  It would be great if there was a python workspace oriented around poetry managed package development.

It's no secret that the [Python packaging ecosystem is a terrible mess](https://drewdevault.com/2021/11/16/Python-stop-screwing-distros-over.html) of different management tools including distutils, setuptools, pip, pipenv, tox, flit, conda, poetry, virtualenv, pyenv, etc etc etc...

In particular, [pyenv and poetry don't appear to always play nice together](https://news.ycombinator.com/item?id=29238906).  

This has likely lead to various issues with using poetry in gitpod in the past: https://github.com/gitpod-io/gitpod/issues?q=is%3Aissue+poetry 

## Describe the behaviour you'd like

Anyway, it would be great if there was just a well tested, dedicated poetry workspace image.

## Describe alternatives you've considered

Some will suggest "use [some other] dependency manager".  This isn't always an option for projects.

## Additional context

Just a thought, but it might be worth considering maintaining a few separate 'flavors' of python workspace image.  For example:

- `gitpod/workspace-python-pyenv`
- `gitpod/workspace-python-poetry`
- `gitpod/workspace-python-[etc]`

Obligatory [XKCD](https://xkcd.com/1987/):

![image](https://user-images.githubusercontent.com/1420654/176935737-987c23e7-4cb9-4525-8916-d74704e4bf0c.png)

**Comment by jenting** [comment]
Code merged.
