### ISSUE TITLE
Java 17 for workspace-full

### ISSUE THREAD

**Issue by jalexcole** [gitpod-io/workspace-images#874]
## Is your feature request related to a problem? Please describe
redhat.java pushed an update requiring java 17 be set up in the homepath. The default jdk is 11, there for the main java extensions do not work unless java 17 is installed.

## Describe the behaviour you'd like
I would recommend moving workspace-full to default at java 17 due to the vscjava.vscode-java-pack provided by redhat vscjava

## Describe alternatives you've considered
Manually configuring the home path in each docker file with java 17 installed. Increases time for start up. 

## Additional context
Extension Notification: "Activating extension 'redhat.java' failed: Java 17 or more recent is required to run the Java extension. Please download and install a recent JDK. You can still compile your projects with older JDKs by configuring ['java.configuration.runtimes'](https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#java.configuration.runtimes)."

**Comment by axonasif** [comment]
See https://github.com/gitpod-io/workspace-images/pull/845#issuecomment-1138212164

**Comment by axonasif** [comment]
@jalexcole you can use `image: gitpod/workspace-java-17:2022-06-20-19-54-55` (tag **2022-06-20-19-54-55** taken from [here](https://hub.docker.com/r/gitpod/workspace-java-17/tags)) on your `.gitpod.yml`. Then you can [see in action](https://www.gitpod.io/docs/config-gitpod-file#see-it-in-action) 😉

**Comment by axonasif** [comment]
That seems weird, what's actually going wrong?

**Comment by axonasif** [comment]
Its recommended to use [custom dockerfiles](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile) for such heavy tasks to save you time.

**Comment by akosyakov** [comment]
Did anyone try to add java 17 to java layer additionally to java 11? Maybe VS Code java is smart enough to found a necessary one without us breaking user apps requiring java 11?

**Comment by jalexcole** [comment]
I think I would like to move the discussion of the issue as more philosophical. The fix is easy enough to require in the dockerfile, however what should the out of the box experience be for anyone starting a project in gitpod? Should a java developer try out spring pet clinic and realize that none of the plugins work and then have to go through and trouble shoot it or should they be able to make changes right then and there and have all of their favorite tools.

**Comment by loujaybee** [comment]
Please note this is blocked / dependent upon: 
- https://github.com/gitpod-io/gitpod/issues/10683

**Comment by loujaybee** [comment]
Update, this is being investigated for possibility to do this in a backwards compatible fashion in: 

- https://github.com/gitpod-io/workspace-images/pull/888
