### ISSUE TITLE
pnpm add -g doesn't work out of the box

### ISSUE THREAD

**Issue by larsivi** [gitpod-io/workspace-images#913]
It seems like PNPM_HOME isn't set, causing add -g to not work. I was able to export it, set to the location of "whereis pnpm", but I'm not sure that is the best solution and I think perhaps it should have been set from the start. To use e.g. prisma/prisma1 (or just update pnpm), this is the canonical way to do it.

I haven't gotten as far yet, but I plan to add these in the gitpod.yml as startup tasks, but presumably those will fail too (unless also the export of PNPM_HOME is run).

**Comment by gengjiawen** [comment]
fixed by https://github.com/gitpod-io/workspace-images/pull/907.
