### ISSUE TITLE
Errors in Gitpod VS Code Terminal

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/workspace-images#925]
### Bug description

Getting the following errors in terminals:

While Opening from `gitpod.new`: 

![image](https://user-images.githubusercontent.com/55068936/189163742-f9f1d750-5019-4caf-bb5c-3e3eb0fb7a88.png)

from a Repository: 

![image](https://user-images.githubusercontent.com/55068936/189163860-60347376-15d9-476f-8f1f-703a507fe945.png)

> Also, See [Internal Discussion](https://gitpod.slack.com/archives/C01RC164G48/p1662139802128469)

### Steps to reproduce

It would affect all workspaces which have Python-related images.

A quick way to Repro. it:

- Open Gitpod VS Code Workspace using [gitpod.new](https://gitpod.new/)
- See terminal 👀 

### Expected behavior

There should be no errors like that:

![image](https://user-images.githubusercontent.com/55068936/189164590-aac50108-49ff-4bda-9cb8-3040698c22fc.png)

### Example repository

- [`localstack-gitpod-demo`](https://github.com/whummer/localstack-gitpod-demo)

**Comment by kylos101** [comment]
Related changes that were made recently:
https://github.com/gitpod-io/workspace-images/pull/895
https://github.com/gitpod-io/workspace-images/pull/912
https://github.com/gitpod-io/workspace-images/pull/922

**Comment by Siddhant-K-code** [comment]
> * The URL to a workspace where you can recreate this problem?

`gitpodio-empty-tlffwpegw8b`

> * Which extensions do you have loaded? I suspect there is variance.

Since, It was from `gitpod.new`, so no specific extensions provided (maybe installed ones are creating issues?)

**Comment by kylos101** [comment]
@Siddhant-K-code what extensions do you see when you open a new workspace from gitpod.new?

I see, and suspect there is an extension sync happening, and maybe I have different extensions, and thus a different experience (no errors):
![image](https://user-images.githubusercontent.com/1272076/189192096-49c5bed5-27cd-4db1-8539-ec4ed8e942d9.png)

**Comment by kylos101** [comment]
@axonasif , can you checkout [this question](https://github.com/gitpod-io/workspace-images/issues/925#issuecomment-1241045456) I asked @Siddhant-K-code and share? I'm unable to reproduce this issue.

**Comment by Siddhant-K-code** [comment]
> I'm unable to reproduce this issue.

Same, I can't be able to reproduce the above in `gitpod.new`
Maybe, it could be due to OpenVSX Extensions sync

**Comment by filiptronicek** [comment]
Just got this one in `gitpod.new` 👀 
<img width="894" alt="image" src="https://user-images.githubusercontent.com/29888641/193585891-ddb9de72-bdb3-4794-a4f3-4f1582840cfe.png">
