### ISSUE TITLE
Update Rust to 1.64.0

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/workspace-images#930]
## Is your feature request related to a problem? Please describe

Because of an issue described in rust-lang/rustup#2417 users cannot manually update Rust after launching a workspace. Attempting to run `rustup update` will fail.

## Describe the behaviour you'd like

I'd like to see Rust updated to 1.64.0.

## Describe alternatives you've considered

N/A

## Additional context

N/A

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3r2dm)

**Comment by gengjiawen** [comment]
Looks like image not syncing: https://github.com/gitpod-io/workspace-images/blob/591b801f4fb9e71fd97d2aeba0d75105d90d6a38/chunks/lang-rust/Dockerfile#L11

**Comment by gengjiawen** [comment]
Or layer caching: https://github.com/gitpod-io/workspace-images/blob/591b801f4fb9e71fd97d2aeba0d75105d90d6a38/chunks/lang-rust/Dockerfile#L7

cc @axonasif

**Comment by c3potheds** [comment]
My new workspaces are still on Rust 1.63, anything I need to do to update them? #933 is still happening so I can't use rustup to update it myself.

**Comment by gengjiawen** [comment]
> My new workspaces are still on Rust 1.63, anything I need to do to update them?

 Should be available on next Tuesday.
