### ISSUE TITLE
Manually publish a version of `workspace-full` that uses Jammy

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#949]
## Is your feature request related to a problem? Please describe

Users would like to use Jammy

## Describe the behaviour you'd like

Users are able to opt-into using the new image, because we'll manually publish it to Dockerhub but not GAR, initially. Why? This way we avoid marking the image as `latest` as per our automation.

## Additional context

https://github.com/gitpod-io/workspace-images/issues/810
https://github.com/gitpod-io/workspace-images/pull/932
https://github.com/gitpod-io/workspace-images/pull/814

**Comment by gengjiawen** [comment]
Any progress on this ? From cpp dev we are expecting this since ubuntu 22.04 bundled gcc with more comprehensive cpp20 support.

**Comment by filiptronicek** [comment]
@kylos101 is this still relevant after https://github.com/gitpod-io/workspace-images/pull/1017?

**Comment by kylos101** [comment]
No, great point, thank you @filiptronicek !
