### ISSUE TITLE
Add php to Gitpod workspace-full image

### ISSUE THREAD

**Issue by outwebbed** [gitpod-io/workspace-images#965]
## Is your feature request related to a problem? Please describe
On the Gitpod [workspace images documentation](https://www.gitpod.io/docs/configure/workspaces/workspace-image) it states:

> By default, Gitpod uses a standard Docker Image called [Workspace-Full](https://github.com/gitpod-io/workspace-images/blob/481f7600b725e0ab507fbf8377641a562a475625/dazzle.yaml#L18) as the foundation for workspaces. Workspaces started based on this default image come pre-installed with Docker, Nix, Go, Java, Node.js, C/C++, Python, Ruby, Rust, **PHP** as well as tools such as Homebrew, Tailscale, Nginx and several more.

And yet while using a custom .gitpod.Dockerfile and specifying the workspace-full image it appears that php is not installed:
```sh
php --version
bash: php: command not found
```

Explored the workspace-full image on Github and saw that php is missing from the specified libraries:
https://github.com/gitpod-io/workspace-images/blob/481f7600b725e0ab507fbf8377641a562a475625/dazzle.yaml#L18

Is this in error or was it intended to remove php from the workspace-full Gitpod image?

## Describe the behaviour you'd like
Add php to the workspace-full Gitpod image

## Describe alternatives you've considered
Of course I can manually install php but would have preferred it be pre-installed on the image.

**Comment by axonasif** [comment]
Hi @outwebbed, php (which is installed in the `nginx` chunk) is not included on the `workspace-full` image.[^1]

That line was probably outdated, thanks for pointing it out 👍 

[^1]: https://github.com/gitpod-io/workspace-images/tree/axonasif/add_docs/chunks#details

**Comment by outwebbed** [comment]
@axonasif gotcha, thanks for the follow up!
