### ISSUE TITLE
Python pip doesn't list all installed packages

### ISSUE THREAD

**Issue by xzmeng** [gitpod-io/workspace-images#985]
### Bug description

Some packages such as `requests` are pre-installed, but not listed with `pip list`.
This is inconvenient to find out all dependencies.

### Steps to reproduce

1. Open https://github.com/xzmeng/xzmeng
2. $ pip list (get no packages)
3. $ python -c "import requests" (ok)

**Comment by axonasif** [comment]
I assume this is related with https://github.com/gitpod-io/workspace-images/issues/984 since you're using zsh.
