### ISSUE TITLE
Add Deno to base GitPod image

### ISSUE THREAD

**Issue by glebbash** [gitpod-io/workspace-images#991]
## Is your feature request related to a problem? Please describe
I am getting really frustrated and tired of copy pasting deno config (.gitpod.yml, .gitpod.Dockerfile) to every repository where I want to use Deno.

## Describe the behaviour you'd like
Would be really nice to have Deno installed in the base GitPod image. It only takes 30mb or so.

## Describe alternatives you've considered
Workarounds are:
- use repository template (not possible when repo already exists)
- install deno using dotfiles (probably not the best idea)
- new feature for GitPod - default gitpod base image for user (might solve all of the simillar problems)

**Comment by gtsiolis** [comment]
Thanks for opening this @glebbash! 🦖 

I've moved this to the `gitpod-io/workspace-images` repository where we track such requests.

**Comment by glebbash** [comment]
Just found out, that it's super easy to install Deno [using dotfiles](https://github.com/gitpod-samples/demo-dotfiles-with-gitpod/blob/main/scripts/deno_configure.sh) and I don't see any problems with this setup for now.

@gtsiolis you can close this issue if this is the recommended way to install Deno in GitPod.

**Comment by gtsiolis** [comment]
Thanks for coming back to this, @glebbash! Closing the issue for now.

Here're some docs around this, see https://www.gitpod.io/docs/introduction/languages/deno

**Comment by glebbash** [comment]
@gtsiolis  Should the docs mention the dotfiles approach? As it is much faster because you don't have to wait for full image build.
