### ISSUE TITLE
[python] Add gitpod/workspace-python-3.11

### ISSUE THREAD

**Issue by obaltian** [gitpod-io/workspace-images#993]
## Is your feature request related to a problem? Please describe
Python3.11 has been officially released this year and should be supported by such generic tools as gitpod, it does not contain any major changes breaking backwards compatibility with 3.10.
Can we add support for the newest python major version to provide up-to-date software?

## Describe the behaviour you'd like
A new image `gitpod/workspace-python-3.11` added to a list of provided images.

## Describe alternatives you've considered
You may update pyenv (since by default it is outdated in image) and install python3.11 in __init__ task, but then my prebuilds take 5 mins instead of 2 (without python3.11 installation). This is not comfortable for everyday work, so can not be considered as an alternative:
```
cd ~/.pyenv && git pull && cd -;
pyenv install python3.11
pyenv global 3.11
poetry env use 3.11
[...]
```
Too much extra movements from end user.

## Additional context
[Link to pyenv update request](https://github.com/gitpod-io/workspace-images/issues/987) (which may be useful for python update).

**Comment by Furisto** [comment]
@obaltian We have added an image for Python 3.11: https://hub.docker.com/r/gitpod/workspace-python-3.11
